### ISSUE TITLE
Better way to integration test wheels that we build in our examples

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#1002]
We'll soon start releasing a runfiles package as a wheel, while our examples continue to load it with a dep on the rules
https://github.com/bazelbuild/rules_python/blob/bd3a7197a295ddcb37414e5723da6c2f41b806ee/examples/pip_parse/BUILD.bazel#L80
and a funny-looking import
https://github.com/bazelbuild/rules_python/blob/bd3a7197a295ddcb37414e5723da6c2f41b806ee/examples/pip_parse/pip_parse_test.py#L8

Ideally we want to:
- build our wheel using `--stamp` and some fictional version label (or just 0.0.0)
- use some mechanism so the examples repository rules find our wheel on disk and create a `@pypi__runfiles` external repo for it just like it would happen if we fetched it from a remote registry
- example now looks just like user code with a `requirements("runfiles")` dep

I tried some things:

1. In WORKSPACE, maybe use a `whl_library` directly -  but it seems like this still calls to `pip download`. Maybe it could be given a local path?
2. in `requirements.in`, do the python-idiomatic thing of a `-f ../../path/to/runfiles.whl` so that `requirements.lock` gets a `--find-links runfiles-1.2.3-py3-none-any.whl` line, then make `pip_parse` do the right thing with local files

Ran out of time for today so punting for someone else...

**Comment by rickeylev** [comment]
Few thoughts.

A rule to produce whl files. This is py_wheel, right? It looks like it mostly does
what we want. The only complication I see is specifying the version string. I would say we should add
a feature to `py_wheel`: The ability to get the `version` attribute from a user defined
flag. This would let us override, on the command line, what its version is. For the
production build, we can set it to the tag version. For the integration test, we can
set it to e.g. 0.0 like you suggest. So in the BUILD file, we have this: `py_wheel(..., version_flag="//python/runfiles:runfiles_version")`

Next, yeah, a rule that can consume a local file or build artifact for the whl instead of going through pip/pypi. Maybe add it to `py_import`? That rule says it's for egg files, and has a comment about adding whl support. Usually the "$lang_import" rules I've seen are to handle pre-built artifacts like whl (java_import for jars, cc_import of prebuilt libraries, etc), so that matches convention.

Finally, putting it all together, the test looks something like:
```
# BUILD
py_wheel(name="runfiles_whl")
py_import(name="runfiles", whl=":runfiles_whl")
py_test(name="runfiles_test", deps=[":runfiles"], ...)

# runfiles_test.py
<verify import runfiles succeeds>
```

The test can also have the .whl as a data dependency and then manually inspect it to make sure metadata etc is set.

Note that this isn't an integration test, as it doesn't go through e.g. the usual requirements and pip stuff. Which I think is OK for now.

I do like the general idea of making the requirements.txt stuff able to not download from pypi (or otherwise make it easier to specify an alternative index or source of things), but that might be a bit big of change? We mostly just want to have some confidence our wheel is building and can be used.

**Comment by jvolkman** [comment]
[pycross_wheel_library](https://github.com/jvolkman/rules_pycross/blob/main/pycross/private/wheel_library.bzl) is basically your `py_import`, I think
