### ISSUE TITLE
py_proto_library doesn't work for well-known types (Timestamp, Any, etc)

### ISSUE THREAD

**Issue by ksteuck** [bazelbuild/rules_python#1005]
# 🐞 bug report

### Affected Rule
 The issue is caused by the rule:  Possibly `py_proto_library` but maybe the culprit is in `rules_proto`  or somewhere in between the two.

### Is this a regression?
No

### Description
the newly added `py_proto_library` does not work for well-known types.

## 🔬 Minimal Reproduction

```
load("@rules_cc//cc:defs.bzl", "cc_proto_library")
load("@rules_python//python:proto.bzl", "py_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "my_proto",
    srcs = ["my.proto"],
    deps = [
        "@com_google_protobuf//:any_proto",
    ],
)

cc_proto_library(
    name = "my_cc_proto",
    deps = [":my_proto"],
)

py_proto_library(
    name = "my_py_proto",
    deps = [":my_proto"],
)
```

```
$ cat my.proto 
syntax = 'proto2';
import "google/protobuf/any.proto";

message Foo {
}
```

```
$ bazel build my_cc_proto 
INFO: Analyzed target //:my_cc_proto (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:my_cc_proto up-to-date:
  bazel-bin/my.pb.h
  bazel-bin/my.pb.cc
  bazel-bin/libmy_proto.a
  bazel-bin/libmy_proto.so
INFO: Elapsed time: 0.205s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

## 🔥 Exception or Error

<pre><code>

$ bazel build my_py_proto
INFO: Analyzed target //:my_py_proto (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: .../.cache/bazel/_bazel_kostik/12e5dc32b4a1cb78e6b68d6d521b6ae5/external/com_google_protobuf/BUILD.bazel:263:14: output 'external/com_google_protobuf/_virtual_imports/any_proto/google/protobuf/any_pb2.py' was not created
ERROR: .../.cache/bazel/_bazel_kostik/12e5dc32b4a1cb78e6b68d6d521b6ae5/external/com_google_protobuf/BUILD.bazel:263:14: Generating Python proto_library @com_google_protobuf//:any_proto failed: not all outputs were created or valid
Target //:my_py_proto failed to build
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Build label: 6.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:52:35 2022 (1671465155)
Build timestamp: 1671465155
Build timestamp as int: 1671465155
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
96621391e7e8861eb448fb94b49aa1fcb9f45ba7
  </code>
</pre>
+latest `rules_proto` and `rules_cc`

**Anything else relevant?**

**Comment by harrisonfang-helm** [comment]
Ran into this issue as well. Could be similar to https://github.com/protocolbuffers/protobuf/issues/6666. I was able to get this working by using the grpc implementation instead: https://github.com/grpc/grpc/blob/ac7faf75ba9b3c373a68acd18f08eb974e603ad5/bazel/python_rules.bzl#L154

**Comment by rickeylev** [comment]
I think one bug might be, in rules_python py_proto_library, the @com_google_protobuf//:protobuf_python dependency isn't having its PyInfo mixed into the output. That dependency eventually points to [protobuf's //python:protobuf_python](https://github.com/protocolbuffers/protobuf/blob/main/python/BUILD.bazel#L19), which is a py_library. At the top of that build file it says:

> Most users should depend upon public aliases in the root:
>    //:protobuf_python
>    //:well_known_types_py_pb2

I'm not sure if that's the _whole_ issue, but probably at least part of it.

Manually adding those dependencies to any py_library depending on a py_proto_library will _probably_ work around the issue. (And I think was reported as such in a the linked to issue). But yeah, it shouldn't be necessary to manually do that.

I'm not sure that really explains the error message about a file not being generated. That is a bit strange. The aspect should be visiting all the necessary files and generating them. The logic for that is pretty simple and mostly just calls back into the proto apis to do so.

**Comment by rickeylev** [comment]
I'm starting to think this is a bug on the proto side. If I comment out the code generation when it visits the `:any_proto` target, everything works OK. From what I can tell, those protos are part of the runtime itself so don't need to be generated. However, I don't see any APIs or clean way to detect whether or not code needs to be generated.

I found some design doc discussion that seemed to talk about these WKT and what sounds like this exact problem.

@comius it looks like you wrote the design doc for these apis? Do you have any insight?

Otherwise, I guess the hacky fix here is to check for the any protos somehow before trying to generate the code, and just skip if it's them. This will be kinda fragile, though.

**Comment by chancila** [comment]
It seems in bazel's starlark-ified proto rules they are using `proto_common.experimental_should_generate_code` to check if some given source files should be compiled. It basically checks ProtoLangToolchainInfo.provided_proto_sources. 

Probably need to add the proto files protobuf_python to https://github.com/bazelbuild/rules_python/blob/main/python/private/proto/BUILD.bazel#L38 and make use of `proto_common.experimental_should_generate_code`

**Comment by sfc-gh-mussakli** [comment]
We are running into this exact issue as well. Are there any known workarounds?

**Comment by mvgijssel** [comment]
Same problem in https://github.com/mvgijssel/setup/pull/310/files. Validated that https://github.com/rules-proto-grpc/rules_proto_grpc works, but that is a lot less trivial to install as it does not have bzlmod support yet.

**Comment by rickeylev** [comment]
> It seems in bazel's starlark-ified proto rules they are using proto_common.experimental_should_generate_code to check if some given source files should be compiled. It basically checks ProtoLangToolchainInfo.provided_proto_sources.

Hm, yeah. [java_proto_library](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/java/proto/java_proto_library.bzl#L54) does that; i see the same with cc_proto_library.

That said, in Google-internal py_proto_library (which is nearly identical to what's in rules_python), we don't have that check, either, and these WKT Just Work (I assume so; haven't heard otherwise). So, something weird is going on.

If adding the `proto_common.experimental_should_generate_code` guard is the correct fix, then great! That said, I'd like to have a proto_common owner verify this API is stable enough to use outside of Bazel itself.

**Comment by hvadehra** [comment]
I think this is fixed at head by https://github.com/bazelbuild/rules_python/commit/1a333cecd73af9916e89b1e1a33fed73d913eb49. So a new release should fix things.
