### ISSUE TITLE
One entry point in WORKSPACE for managing various python project requirements

### ISSUE THREAD

**Issue by bakkiraju** [bazelbuild/rules_python#1134]
I am looking for loading a reqs.bzl file in my WORKSPACE and manage all further requirements in .bzl files instead adding multiple pip_parse , load() and install_deps() commands to my WORKSPACE file

I could call pip_parse, load() and install_deps inside my reqs.bzl and hence tried using compile_pip_requirments() but keep getting 
```
ERROR: Traceback (most recent call last):
        File "/home/ubuntu/bazel-tests/python-bazel-ex/WORKSPACE", line 11, column 10, in <toplevel>
                load_reqs()
        File "/home/ubuntu/bazel-tests/python-bazel-ex/reqs.bzl", line 5, column 29, in load_reqs
                compile_pip_requirements(
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/8a440f7da91b22a75cd182cbf4234de9/external/rules_python/python/pip_install/requirements.bzl", line 40, column 21, in compile_pip_requirements
                native.filegroup(
Error in filegroup: filegroup cannot be in the WORKSPACE file (used by //external:pyreqs)
ERROR: Error computing the main repository mapping: error loading package 'external': Package 'external' contains errors

```
the full example is in here

https://github.com/bakkiraju/python-bazel-ex

also tried to post the question stack overflow here with more details

https://stackoverflow.com/questions/75771422/one-entry-point-in-workspace-for-managing-various-python-project-requirements

**Comment by martis42** [comment]
@bakkiraju 
Your example seems to mix things up. For example, `compile_pip_requirements` is supposed to be in a BUILD file, not the WORKSPACE file or a .bzl file.

You can see a good example how to use rules_python and the dependency management based on requirements files here: https://github.com/bazelbuild/rules_python/tree/1383bd4fa06c7c449156913f123c452533cdd724/examples/pip_parse

**Comment by martis42** [comment]
Since you don't want to add code directly to the WORKSPACE file, you can also look at this project of mine: https://github.com/martis42/depend_on_what_you_use

I am not saying this is the ideal way to do it, but it works and minimizes the amount of code in the WORKSPACE file.

The loading of rules_python and the dependencies is split into multiple [dependencies_step_x.bzl](https://github.com/martis42/depend_on_what_you_use/tree/main/third_party) files. One cannot put all steps into a single file (in short, you can't have a loading statement from an external workspace which is not yet available).
