### ISSUE TITLE
Does gazelle plugin support multiple `requirements.txt` in the same `WORKSPACE`?

### ISSUE THREAD

**Issue by ofey404** [bazelbuild/rules_python#1165]
# 🚀 feature request

Besides, does gazelle plugin support multiple requirements.txt in the same WORKSPACE?

I plan to use it in a python monorepo.

### Relevant Rules

`@rules_python_gazelle_plugin`

### Description

An example directory structure is like this:

```
.
WORKSPACE
BUILD.bazel
requirements.txt
src/
    our_main_package/...
example/
    sub_package_a/
        requirements.txt
    sub_package_b/
        requirements.txt
```

### Describe the solution you'd like

I have no idea, if `rules_python` natively support it.

### Describe alternatives you've considered

Create multiple WORKSPACE.

It's not preferred because I work on an existing bazel monorepo.

**Comment by ofey404** [comment]
Is there anybody interested in this?

**Comment by arrdem** [comment]
So there's a couple things here.

First off, the current `pip_parse` implementation for pre-bzlmod workspaces absolutely does support multiple usage. You just call `pip_parse` several times, once for each `requirements_lock.txt` you're interested in with distinct workspace names. The generated workspaces which implement each requirement are namespaced by the name provided to the `pip_parse` call, so you can for instance have multiple versions (or architectures or whatever) of `requests` running around. Until recently a repo I own did exactly this in order to cope with differences in locked requirements across platforms. Just parse all the requirements you could possibly need into unique packages and create a `requirement()` macro that dispatches to the "right one" later.

Now the problem with doing this generally is "what is the right version to use" at any given point? Bazel has no dependency resolution engine* - it expects that you've already resolved and locked your dependencies. The multiple `pip_parse` situation I used to have only used one set of requirements at any given time. This avoids multiple dependency problems where say two libraries depend on different "requests" but something also depends on both of them at once. The single, global version choice strategy is really the only way to obviate this problem.

Now, you absolutely could just have several `pip_parse` calls and use the `requirement()` macro from each in different parts of the codebase. From a mechanical perspective that'll work. You'll just immediately have weird problems if the dependency graphs cross.

------

* bzlmod may in some ways change this

**Comment by ofey404** [comment]
> so you can for instance have multiple versions (or architectures or whatever) of `requests` running around.

Yes, I've run into the `request` hazard several times.

@arrdem I absolutely agree with you, if we start a monorepo from scratch, we should always keep 1 requirements.txt.

I ask this because I'm considering migrating a legacy giant repo to bazel, which has multiple requirements.txt.

Thank you for your detailed explanation!

(About the weird dependency graph cross problem, I've encountered it in golang gazelle, when I try to get multiple go.mod in a monorepo.)

====

I don't quite familiar with bzlmod. So should we keep this issue hanging around for some time, rather than close it?
