### ISSUE TITLE
Entrypoint is not implemented for multiple pips

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#1262]
So entry point does not work in multiple pips. It is not supported. So I have to have two different templates or modify code.

The pip hub, whl_alias both need to be modified.  The key is that we have this:

```
def entry_point(pkg, script = None):
    """entry_point returns the target of the canonical label of the package entrypoints.
    """
    if not script:
        script = pkg
    return "@@rules_python~override~pip~pip_39_{}//:rules_python_wheel_entry_point_{}".format(_clean_name(pkg), script)
```

Created by a repo rules like `@pip_39_pylint`.  But that is one of the spokes that has "39" for the Python version.

In the pip hub we need to have the capability to have:

```
def entry_point(pkg, script = None):
    """entry_point returns the target of the canonical label of the package entrypoints.
    """
    if not script:
        script = pkg
    return "@@rules_python~override~pip~pip_{}_{}//:rules_python_wheel_entry_point_{}".format(_clean_name(pkg),python_version, script)
``` 

We need the Python version in the pip hub via a select statement.

_Originally posted by @chrislovecnm in https://github.com/bazelbuild/rules_python/pull/1254#discussion_r1221659188_

**Comment by rickeylev** [comment]
I've tagged this bzlmod because I consider it bzlmod specific -- we're using the multi-pip impl under the hood for bzlmod, but need it to support the same features as non-multi-pip. Workspace multi-pip not supporting entry_point is fine and just continues what it does today.

**Comment by chrislovecnm** [comment]
@rickeylev ahat about the user providing the configuran information, or how about  put this into gazelle?

**Comment by aignas** [comment]
I have created a PR on solving this in a slightly different way than @rickeylev proposed and did some cleanup after that.

**Comment by rickeylev** [comment]
> I have created a PR on solving this in a slightly different way 

To summarize: This is PR #1294. The net differences to what I posted are:
  * whl_library_alias isn't used in the bzlmod impl anymore. Instead, the hub, using select(),
    directly points to the backing whl_library targets. (This makes sense; the hub is
    doing what whl_library_alias was doing, so we don't need two levels of indirection).
  * The entry_point() function computes and returns the select() expression directly (instead of returning a label to an alias with that expression).

Having entry_point() return the select() expression directly is clever :). The big pro is it avoids having to download/extract every version-specific wheel to construct the select() expression for an entry point. This is because the reference to the version-specific wheel repo is as a target (analysis phase) instead of a load statement (loading phase).

The main downside is the _concrete_ return type of entry_point() slightly changes: it used to be a string label; now it's a select expression. The return type is still "A thing that can be resolved to a target". I'm not sure how much this matters? Where a string label is required vs where a select() can be directly put is a bit inconsistent. e.g., `alias.actual` can be either, but you can't put a select as an element of a `deps` list, for example. Similar with e.g. `$(location)` make vars. At the least, this is easily worked around: define your own alias.

There are some other ideas to solve this, but they have their own drawbacks
  * Have entry_point() generate an alias itself. This is iffy since entry_point() might be called multiple times, so we'd need to conditionally generate an alias().
  * Have pip.parse() take a list of entry point names.
  * Introduce e.g define_entry_point() which defines an alias for you; you have to manually call it.

In any case, I've approved the PR since:
  * There isn't an existing implementation for this for bzlmod already, so the "change" in return value isn't technically a change.
  * It's easily worked around
  * The docs recommend putting entry points behind an alias anyways.

----

More concretely, the build files look something like this, given a pip hub named `@pip` and a `pylint` wheel for Python 3.8:

```
# pip/requirements.bzl:
def entry_point(pkg, script):
  choices = {
    "<is py X.Y condition>": "@@pip~whatever//{pkg}/bin_{version}:{script}",
    ...repeat for each registered python version...
  }
  return select(choices)

# pip/pylint/bin_py38/BUILD
load("@pip_py38_pylint//:entrypoints.bzl")
for each script in entrypoints.bzl:
  alias(name=script, actual="@pip_py38_pylint//:{script}")

# pip_py38_pylint/BUILD
<existing code to generate py_binary for each entry point>

# pip_py38_pylint/entry_points.bzl
# This is newly generated by wheel_installer.py
entry_points = ["epylint", ...]
```

**Comment by aignas** [comment]
FYI, I am doing some refactorings to fix transitions for entry_points and to split the big experimental PR into multiple smaller parts. Working on #1330 turned out to be a useful thing because I am modifying the `whl_library` repo rule quite a few times and doing the refactor and tidy up before the feature additions makes testing easier.
