### ISSUE TITLE
Example for multiple Python version for a toolchain built using py_runtime

### ISSUE THREAD

**Issue by guillaumep** [bazelbuild/rules_python#1456]
# 🚀 feature request

The example in `rules_python/examples/multi_python_versions` applies to Python runtimes dowloaded from the `python-build-standalone` project. I'm trying to find a way to setup multiple Python versions for my build using a toolchain built from`py_runtime` (and I guess `py_runtime_pair`) so I could run tests for two different Python versions in my monorepo, but using the system-installed interpreters. I can't use the `python-build-standalone` project since it can't load extension modules.

I've tried reading all of the documentation but could not find a way. Could you enlighten me? Or could I suggest that such documentation could be written?

**Comment by rickeylev** [comment]
The two basic pieces are:
1. When defining a toolchain, make sure to include the python version constraint in target_compatible_with. Make sure these toolchains are registered _before_ a Python toolchain that _doesn't_ have the extra constraint.
2. When trying to use the toolchains, make sure to use the multi-version aware rules. Your two options here are:
   1. (suggested) Use the generated, version-bound symbols by registering a hermetic toolchain (note they are bound to the version, not the toolchain), or
   2. Using the lower-level `@rule_python//python/config_settings:transition.bzl#py_binary` symbols directly (where you'll have to specify the exact python version you want to use)

Looking at the generated BUILD files should also be illustrative. You basically just copy what those do, but set `interpreter_path` instead of `interpreter`. I think you can find them by looking around in the "output root", which is where bazel puts generated repositories. `bazel info output_root` maybe? I can't remember the exact command. Root around in the various directories and you'll eventually see directory names matching the generated repository names.

**Comment by guillaumep** [comment]
I think I got it working. Here's my understanding of it.

First define an helper macro named `python_toolchain.bzl`:

```py
def python_toolchain(
        name,
        python_version,
        interpreter_path):
    runtime_name = "{}_runtime".format(name)
    runtime_pair_name = "{}_runtime_pair".format(name)

    py_runtime(
        name = runtime_name,
        interpreter_path = interpreter_path,
        python_version = "PY3",
        stub_shebang = "#!{}".format(interpreter_path),
    )

    py_runtime_pair(
        name = runtime_pair_name,
        py3_runtime = runtime_name,
        visibility = ["//visibility:public"],
    )

    native.toolchain(
        name = name,
        # That's what enable the selection of the toolchain
        target_settings = ["@rules_python//python/config_settings:is_python_{}".format(python_version)],
        toolchain = runtime_pair_name,
        toolchain_type = "@bazel_tools//tools/python:toolchain_type",
    )
```

`BUILD`:

```py
load("//:python_toolchain.bzl", "python_toolchain")

python_toolchain(
    name = "python3.8_toolchain",
    # The version must be listed in @rules_python//python:versions.bzl
    # It does NOT necessarily correspond to the host interpreter version.
    python_version = "3.8.17",
    interpreter_path = "/usr/bin/python3.8",
)

python_toolchain(
    name = "python3.9_toolchain",
    python_version = "3.9.18",
    interpreter_path = "/usr/bin/python3.9",
)

python_toolchain(
    name = "python3.10_toolchain",
    python_version = "3.10.13",
    interpreter_path = "/usr/bin/python3.10",
)

python_toolchain(
    name = "python3.11_toolchain",
    python_version = "3.11.5",
    interpreter_path = "/usr/bin/python3.11",
)
```

`WORKSPACE`:

```py
# Before loading rules_python:
register_toolchains(
    ":python3.8_toolchain",
    ":python3.9_toolchain",
    ":python3.10_toolchain",
    ":python3.11_toolchain",
)
```

`src/BUILD`:

```py
load("@rules_python//python/config_settings:transition.bzl", "py_binary")

py_binary(
    name = "example_target_38",
    python_version = "3.8.17",
    srcs = ["somefile.py"]
    # ...
)

py_binary(
    name = "example_target_311",
    python_version = "3.11.5",
    srcs = ["somefile.py"]
    # ...
)
```

**Comment by guillaumep** [comment]
I would still like to suggest writing some formal documentation as a feature request, however feel free to close this issue.

**Comment by rickeylev** [comment]
Yep, that looks about right. Just use `@rules_python//python:toolchain_type` (I think it is) instead of `@bazel_tools`. The `@bazel_tools` one is being superceded by rules_python.

**Comment by guillaumep** [comment]
Thanks!

**Comment by chrislovecnm** [comment]
@guillaumep, we always appreciate PRs adding to our docs! 

Closing as requested
