### ISSUE TITLE
Remove `integrity` field from gazelle manifest?

### ISSUE THREAD

**Issue by adzenith** [bazelbuild/rules_python#1465]
# 🚀 feature request

### Relevant Rules

This is a feature request for the Gazelle plugin.

### Description

Right now the Gazelle plugin puts an integrity hash at the bottom of its `gazelle_python.yaml` manifest file. It appears that this sum is a hash [of the manifest file itself](https://github.com/bazelbuild/rules_python/blob/fe33a4582c37499f3caeb49a07a78fc7948a8949/gazelle/manifest/manifest.go#L31-L33). Any time any package is added or removed, or a package version changes, this sum is recalculated. This makes it difficult to use tools like Renovate to upgrade our Python packages, because if it wants to upgrade multiple libs the PRs conflict with each other: each one modifies that sum separately.

### Describe the solution you'd like

I am curious if the sum can just be removed from the file. Could the manifest test instead just recalculate what the file should look like and then check if the file on disk matches? This is how e.g. the requirements.in -> requirements.txt calculation happens, and so you hit merge conflicts if alphabetically adjacent packages get upgraded, but in the usual case this avoids merge conflicts.

### Describe alternatives you've considered

Right now it's just a lot of rebasing and recalculating this hash.

Thanks!

**Comment by aignas** [comment]
@f0rmiga, do you remember the initial motivation for having the `integrity` field in there?

**Comment by adzenith** [comment]
Would there be interest in a pull request to remove it?

**Comment by aignas** [comment]
@adzenith, yes I'd be interested in making the attribute optional which would stop including the integrity in a backwards compatible way.

**Comment by aignas** [comment]
Looking at this a little more it seems that the following change would have to be made:
* Migrate `go_test` to see if the manifest is stale to `diff_test`.
* Migrate `go_binary` to `run_binary` or `genrule` to generate the manifest file that can be used with `diff_test`.
* Migrate to a python script (that should work on windows) to fix a `diff_test` failure.

Maybe some of this could be done entirely in Python without any `rules_go` usage, which could be a plus, because `gazelle` users could prebuild the `gazelle` binary and then not need to download the whole golang toolchain to just check that the manifest is up-to-date.

I think right now the `integrity` is used to check that the `gazelle_python.yaml` has been generated from the `requirements.txt` file. However, I've seen `gazelle_python.yaml` differing between platforms with the same `requirements.txt` (e.g. numpy includes an `.so` library that becomes part of `gazelle_python.yaml`). This means that using the `integrity` yields to best effort behaviour. Given that we will have all of the wheels on disk when running `bazel test //...`, we should probably just rely on the CAS to give us the output of the `modules_mapping` and remove this bespoke cash invalidation technique.

**Comment by adzenith** [comment]
You can now get rid of the integrity field by not passing the `requirements` argument to `gazelle_python_manifest`!
