### ISSUE TITLE
rules_python docs testcases are failing with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1481]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3367#018b176e-b253-4172-bcd8-467787240687

Platform : Multiple

Logs:
```
//docs:check_pip                                                         FAILED 
//docs:check_pip_repository                                              FAILED 
//docs:check_py_cc_toolchain_info                                        FAILED
//docs:check_py_console_script_binary                                    FAILED
//docs:check_python                                                      FAILED
Executed 91 out of 94 tests: 86 tests pass, 5 fail remotely and 3 were skipped.
```

Steps:
```
git clone https://github.com/bazelbuild/rules_python.git
git reset f5d01c730d5629b520c408c20eaffbf10f25154d --hard
export USE_BAZEL_VERSION=66ac39c793605cc08d6f3c0a83401f3fdbb03f1b
bazel test --test_tag_filters=-integration-test  -- ...
```
culprit : [32cc97e0a9a5810ab5469708f768666022c27642](https://github.com/bazelbuild/bazel/commit/32cc97e0a9a5810ab5469708f768666022c27642)
CC Greenteam @mai93

**Comment by rickeylev** [comment]
Is this perhaps an issue with stardoc?

Looking at the diff, it looks like leading spaces of new lines have changed.

**Comment by rickeylev** [comment]
Yeah, this looks like an relatively innocuous behavior change in stardoc. Making this pass in both Bazel versions at the same time might be tricky.

Is there some way we can ignore these failures for now? Adding a magic tag or some such? I just don't think its worth it to try and make docs generate the exact same content under both versions.

It makes sense to make sure the docs can build in upcoming bazel versions, but these golden tests are inherently brittle. We have these tests because otherwise we forget to update the docs when docstrings are changed, so we want to keep these tests around.


Case 1: repr of function defaults has changed:

```
(old) | <a id="compile_pip_requirements-py_binary"></a>py_binary |  the py_binary rule to be used.   |  `<function py_binary>` |
(new) | <a id="compile_pip_requirements-py_binary"></a>py_binary |  the py_binary rule to be used.   |  `<function py_binary from //python:py_binary.bzl>` |
```

Note how the function is repr'd. The old (bazel 6) output is just the function name. The new (bazel 7) output includes the file from which it came.

This can probably be worked around by using None as the default and doc'ing what the default is.

Case 2: Ordering of output has changed:

For the pip.md generation, the `whl_library_alias` rule moved from being at the start, to being at the end. It's not clear why it was at the start originally. Maybe because the ordering used to be (rules, macros)? And now the ordering is simply alphabetical? Working around this will probably be annoying...

Case 3: builtin providers are now documented

In python.md (which comes from //python:defs.bzl), the PyInfo and PyRuntimeInfo providers are now being documented; they weren't previously. I'm not sure if this is a stardoc change, or due to the underlying implemention of them being in Bazel-builtin Starlark instead of Java-implemented.

**Comment by aignas** [comment]
+1 for disabling the `diff_test` against `bazel HEAD`, but at the same time it might be nice to start versioning our docs - have `docs/5.x`, `docs/6.x`, `docs/7.x` that way we can accommodate these differences. When `7` is released we may need to deal with different docs on `bazel 7` and `bazel 6.4` which would require something like this.

**Comment by mai93** [comment]
@meteorcloudy can we disable this test against bazel HEAD but keep it for released bazel?

**Comment by meteorcloudy** [comment]
Yes, you can use `skip_in_bazel_downstream_pipeline`

For example: https://github.com/bazelbuild/rules_foreign_cc/blob/ef3031e3874b8282c717fd3341ef5fbad2591b8f/.bazelci/config.yaml#L202-L205

**Comment by rickeylev** [comment]
That looks like it operates at the job level. Is there one that can operate at the test level instead?

**Comment by meteorcloudy** [comment]
> That looks like it operates at the job level. Is there one that can operate at the test level instead?

Nope, can you split those tests into different jobs?

**Comment by alexeagle** [comment]
Just to raise the less-complex possibility on this thread - was the change to the leading whitespace intentional? We're going to have this problem in dozens of rulesets so I'm not excited to call this resolved by a change in rules_python

**Comment by rickeylev** [comment]
> can you split those tests into different jobs?

Ehhh, it might be rather tight. We only have 2 CI slots left, and I was going to use those for testing the starlark implementation on windows and mac.

Hm...maybe we can detect the `BUILDKITE_PIPELINE_NAME=Bazel@HEAD + Downstream` env var and tunnel that through to set some tags that CI ignores...

I'm thinking it'l make more sense to just disable these tests for now. We'll have to reconfigure CI to only run a single Bazel version for doc generation no matter what. Having to manually update docs until Bazel 7 lands and we can reconfigure CI doesn't seem like a huge deal.

**Comment by rickeylev** [comment]
Actually, don't worry about this -- I'm about ready to delete these doc tests as part of moving our docs to sphinx. Should be done in the next day or so.

**Comment by meteorcloudy** [comment]
I'll implement the feature on the CI side anyway, since it might be needed in future, but this removes the urgency on it. Thanks!

**Comment by rickeylev** [comment]
The offending tests have been deleted, closing.
