### ISSUE TITLE
The 0.27.0 sphinx docs on https://rules-python.readthedocs.io/en/latest/ can not be viewed

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_python#1568]
I am not sure what the exact behaviour should be, but I would expect the docs for the 0.27.0 to be visible when going to https://rules-python.readthedocs.io/en/latest/.

**Comment by aignas** [comment]
It seems that the documentation was in https://rules-python.readthedocs.io/en/stable/

**Comment by aignas** [comment]
I guess it was a little confusing at first because I could not see the version number anywhere, but it is fine for the time being.

**Comment by rickeylev** [comment]
Oh hm, but stable doesn't show 0.27.0. I think in order to see any new activated versions, a new build has to be performed. Well, that's annoying. I've rebuilt stable so 27 shows up, at least.

I think this is supposed to be fixed by an upcoming flyout integration (which injects the flyout code at runtime instead of embedding it at build time). I'm not entirely sure if that is enabled for us or if or if our build activates it, though.

**Comment by rickeylev** [comment]
Er, huh. Now stable is showing 27 in the flyout. But it isn't done building yet? Maybe a cache? Or maybe it only flushed the cache after I pressed build...?

IDK :shrug:
