### ISSUE TITLE
No matching toolchains when using `current_py_cc_headers` with WORKSPACE.

### ISSUE THREAD

**Issue by lalten** [bazelbuild/rules_python#1669]
# 🐞 bug report

### Description

Can not use `@rules_python//python/cc:current_py_cc_headers` in WORKSPACE mode because the toolchain fails to resolve. The WORKSPACE file is setting up a hermetic interpreter via `python_register_toolchains`.

Note that the target works as expected when using a MODULE.bazel.

## 🔬 Minimal Reproduction

See repro repo: https://github.com/lalten/current_py_cc_headers

## 🔥 Exception or Error

`@@rules_python//python/cc:current_py_cc_headers (5b7f3da): No matching toolchains found for types @@rules_python//python/cc:toolchain_type.`

## 🌍  Your Environment

**Operating System:** `ubuntu-latest`
**Output of `bazel version`:** `7.0.0`
**Rules_python version:** `0.27.1`

**Comment by rickeylev** [comment]
Ah, i think what's happening is the workspace code path registers a specific target instead of `:all` (which is what bzlmod does). https://github.com/bazelbuild/rules_python/blob/main/python/repositories.bzl#L583

Should be a simple fix to have it register the additional toolchain.

In the meantime, you can work around this by adding native.register_toolchain() to your workspace. Something like `@<name>_toolchains//:all`, where `<name>` is the name of the python runtime repo that was used (usually `@python` or `@python_3_11`). Or register the specific platforms you're interested by doing using `@<name>_toolchains//<platform>_toolchain`, where`<platform>` would be e.g. linux_x86_64
