### ISSUE TITLE
python_library_naming_convention Gazelle directive is ignored when python_generation_mode set to "file"

### ISSUE THREAD

**Issue by yechuan51** [bazelbuild/rules_python#1677]
# 🐞 bug report

### Affected Rule

rules_python

### Is this a regression?

I tried earlier version of rules_python, but it appears that earlier version either don't support python_generation_mode=file or produce the same result. 

### Description

python_library_naming_convention appears to be ignored if python_generation_mode is set to "file" mode. When I set "python_library_naming_convention" to "$package_name$_lib" and "python_generation_mode" to "file", the generated python_library target is still "$package_name". 

But once I remove "python_generation_mode" rule, the generated target shows up with the expected name(i.e. foo_lib). 

## 🔬 Minimal Reproduction

I don't yet have the time to produce a minimal reproduction yet. But if needed, I can look into this. 

It should be as simple as setting both directive and run Gazelle. 

## 🔥 Exception or Error

python_library_naming_convention is ignored.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 14.1.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 7.0.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Dec 11 17:00:42 2023 (1702314042)
Build timestamp: 1702314042
Build timestamp as int: 1702314042
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.27.1
  </code>
</pre>

**Anything else relevant?**

**Comment by aryamccarthy** [comment]
This is also true about `py_binary_naming_convention`.

**Comment by aignas** [comment]
Since in file mode we don't want to name the targets by the package name (we would have clashes if for more than one py_library or py_binary, we would need to add a new token for defining the convention to mean the src file. I think this ticket is a feature request and I am wondering if such a convention is really needed given the discussion in #1664.

@yechuan51 and @aryamccarthy, what are your thoughts? Is it still needed?
