### ISSUE TITLE
Using strip_path_prefixes in py_wheel can lead to import errors when running the installed wheel

### ISSUE THREAD

**Issue by sfriedowitz** [bazelbuild/rules_python#1694]
# 🚀 feature request

### Relevant Rules

This request pertains to the `py_wheel` rule.

### Description

This is somewhat of a feature request, but I am also just seeking some guidance on any current workarounds to this issue.

I've encountered an issue when trying to use the `py_wheel` rule with the `strip_path_prefixes` argument. My repository has a directory structure along the lines of `projects/python/namespace/...`, and I am trying to distributed a wheel for the Python code within `namespace`. The Python source code is written with absolute imports from the workspace root, e.g., `from projects.python.namespace import X`, so that the imports align with the runfile structure for `py_binary` targets.

When creating a wheel for this package, it is desirable to use `strip_path_prefixes` to remove the top-level `projects/python` folders from the distribution. However, using this feature leads to broken wheels because the absolute imports in the source code do not align with the modified directory structure in the resulting wheel.

### Describe the solution you'd like

I am curious about a feature that would allow for replacing the imports in the Python source code when using `strip_path_prefixes`. It seems like a flag along the lines of `rewrite_imports = True/False` could be passed down to `wheelmaker.py` to control some replacement logic. 

Albeit, this may be a terrible idea because of potential pitfalls of source code string replacements, which is why I am also curious to hear suggestions for workarounds.

### Describe alternatives you've considered

A potential workaround is to maintain the repository without such nested directories. So rather than having the module live at `projects/python/namespace`, we could just place the `namespace` folder at the root of the workspace. The `strip_path_prefixes` functionality would no longer be necessary, and Python imports would be aligned with the directory structure of the packaged code.

I would appreciate any other suggestions for workarounds, both in terms of functionality of the bazel rules as well as other patterns for how to structure our repository. I'd imagine that this is a common issue that people have run into when trying to package their Python code with `py_wheel`.

Thank you!

**Comment by aignas** [comment]
Packaging of the wheel should be just that - no replacements within the source code, because it is easy to have hard to debug issues otherwise.

In this case it is best to use imports that align with the desirable und state and use imports attribute on the py_library so that the rest of the dependants on the 'namespace' project do not break.

You could also use a genrule (or something similar) to rewrite the source code yourself if that is something you would still like, but that is likely to be error prone.

I am going to close this as won't do, as we have a way to make this work via the imports attribute and not use absolute imports with respect to the root of the bazel workspace. For more complex monorepos, IMHO, the publishing story tends to be more complex and one has to make compromises. Especially since there is no good way to test the packaged wheel. I think having a rule to allow for that would be a good feature request, but I'll leave people to file it if it is really needed as it could be just me thinking of how to extend the project. :)
