### ISSUE TITLE
Gazelle produces different manifests on macOS and Linux

### ISSUE THREAD

**Issue by SpencerC** [bazelbuild/rules_python#1702]
# 🐞 bug report

### Affected Rule

 `gazelle_python_manifest`

### Is this a regression?

  No

### Description

Running `gazelle_python_manifest` with the same lock file produces two different results on macOS vs. Linux. On Linux:
<img width="426" alt="Screenshot 2024-01-18 at 4 16 33 PM" src="https://github.com/bazelbuild/rules_python/assets/817672/2de1a8fc-9f19-448f-b68e-3c836deed20b">

Is there a way to fix this through configuration? 

## 🔬 Minimal Reproduction

Require `numpy` or `caio`, run `compile_pip_requirements`, and run `gazelle_python_manifest`.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Sonoma 14.2.1 (23C71)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 6.2.1
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 2 17:00:10 2023 (1685725210)
Build timestamp: 1685725210
Build timestamp as int: 1685725210
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.28.0
  </code>
</pre>

**Anything else relevant?**

**Comment by dududko** [comment]
Faced the same issue. 

Is it correct that `gazelle_python.yaml` should ideally contain only direct dependencies, because for BUILD file generation/update gazelle needs only direct dependencies. It could be that transitive dependencies for different platforms can differ, but this is not important. 

So because of this `module_mapping` should exclude everything which is not common for both/all platforms to keep `gazelle_python.yaml` basically platform agnostic. 

Is my understanding correct?

**Comment by aignas** [comment]
@dududko, yes your understanding is correct.
