### ISSUE TITLE
pip_parse package annotation additive_build_content stops working after 0.26.0

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/rules_python#1839]
# 🐞 bug report

### Affected Rule

pip_parse package annotation additive_build_content stops working after 0.26.0

### Is this a regression?
I believe this is a regression. We use this successfully in 0.26.0 however it has stopped working in 0.27.0 

### Description

It seems that packages are no longer annotated above 0.27.0, if we supply some custom starlark to go in the BUILD file this is no longer added. 

## 🔬 Minimal Reproduction
Modify the WORKSPACE here to switch versions and you can see annotations are not produced above 0.27.0

[rules_python_annotation_broken.zip](https://github.com/bazelbuild/rules_python/files/14934409/rules_python_annotation_broken.zip)

## 🔥 Exception or Error

Annotations are missing

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux + windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
6.4.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.27.0
  </code>
</pre>

**Anything else relevant?**

There as mention of it being broken here: https://github.com/bazelbuild/rules_python/issues/1311 however the version looks too old.  I don't think its related, this is a regression, and my scenario works with 0.23.1.

**Comment by carpenterjc** [comment]
Looking further into this it looks like this change in behaviour is caused because the `requirement("foo")` function now points at an alias in the same repo you get requirement from. Those rules don't know to produce a reference to the actual repo. 

So you need to actually reference the target explicitly. However there isn't a stable documented way to get the annotations in. 

Maybe this now becomes a feature request for a helper function to construct a version stable target name for accessing any annotation.

**Comment by aignas** [comment]
Providing a helper that would do this is not something that is super easy to do because the hub repo is created without knowing the contents of the whl library build files.

Could you maybe ellaborate about what kind of modifications you do to the wheel BUILD.bazel, so that we could find the best way to expose them through the hub repo?

For now you could work around the deficiency by doing
```
use_repo(pip, "pip_311_foo")
```

However, the names of each whl library repo could change and is right now somewhat of an implementation detail of bzlmod.

One thing that we could do here that would work allright, but I am not yet sure if it is the best approach in terms of maintenance point of view is to provide a macro in `@pip//foo:alias.bzl`, that would have the same select statement in the macro form that would exist in `@pip//foo:BUILD.bazel`. The same macro could be reused in the alias building.

This would allow the user to create an alias to any target within the repo, but that raises questions why we would want to do it. If the files within the wheel were exposed via the `data` filegroup then the users of rules_python could be able to just use build actions and genrules for their build logic. I guess I am trying to avoid the ergonomics/maintenance issues that we have with the requirement macros.

An alternative would be to use
```
pip.override(
    hub_name = "pip",
    distribution = "foo",
    aliases = ["bar", "baz"],
)
```

Or do the same via the `whl_overrides` API. However I am not sure if that is better. The ideal would be to have the whl_library targets such that we could do more during the build phase rather than need to setup things during the repository rule phase.

One thing that I had experimented in the past is to parse the additional content string to try to get the labels of extra targets that tho user may define, but that is brittle. I'd really rather let the user to define the list of the extra targets that he/she needs to have aliased instead.

**Comment by aignas** [comment]
FYI #1311 is the older issue on the same topic, so I'll close this one to have fewer items in the issue backlog.
