### ISSUE TITLE
Gazelle: Sanitize distribution names in modules mapping / manifest, not at runtime

### ISSUE THREAD

**Issue by wingsofovnia** [bazelbuild/rules_python#1939]
# 🚀 feature request

### Relevant Rules

* `modules_mapping`
* `gazelle_python_manifest`
* `gazelle`

### Description

Gazelle plugin uses `gazelle_python.yaml` (`gazelle:python_manifest_file_name`) to derive `deps` for py targets. One might expect that a dependency label will be `${manifest.pip_repository}//${manifest.modules_mapping.some.import}`, however, Gazelle does extra sanitisation right before using the mapping value [here](https://github.com/bazelbuild/rules_python/blob/ae1e1a014d88a9862c232daafcb6b1025b2928ae/gazelle/pythonconfig/pythonconfig.go#L266).

Although it is not a big deal when used with `rules_python`, it makes harder to reuse Gazelle plugin with other python rules, more specifically [rules_pycross](https://github.com/jvolkman/rules_pycross), which has a different target naming convention, which is aligned with [Python normalised names](https://packaging.python.org/en/latest/specifications/name-normalization/). In [this ticket](https://github.com/jvolkman/rules_pycross/issues/100), there is an approach (or hack really) described for patching `gazelle_python.yaml` but further sanitisation that happens inside the plugin itself makes it impossible to use.

I do understand that compatibility with other rules most likely isn't of highest priority, here are some other reasons:
* It would be slightly less confusing when target name derivation (normalisation / alignment) happens in once place, rather than in `modules_mapping` and/or `gazelle_python_manifest` and/or plugin itself.
* Given that there are ongoing efforts to #1360, it might be a good improvement going forward.

### Describe the solution you'd like

* Do not `SanitizeDistribution` in `pythonconfig.Config#FindThirdPartyDependency`, take the value as is.
* Do `SanitizeDistribution` in `modules_mapping`, or `gazelle_python_manifest`. I'd say `modules_mapping` is best but please advice.

**Comment by aignas** [comment]
A few thoughts here before I forget :)

I think that returning the mapping of import to python package from `modules_mapping` is still a good idea, because given a `whl` file the returned values will be the same, no matter what hub repo the file is used in (this is useful for bigger monorepos where there could be many requirements files).

Being able to have a `gazelle_python.yaml` file (or a directive) that allows us to configure the `gazelle` plugin to not rely on any naming convention would be ideal, but not sure if it is possible here. Having `target_convention: @pypi//{distribution}.replace("-", "_")` in the YAML could be a great way for the user to control that, but I am not sure it is feasible. Having `@pypi//:{distribution}` is another alternative that could work. That would at least fix the `@pypi//:{distribution}` vs `@pypi//{distribution}` differences.

Regarding `-` vs `_` it does sound like it would be best to converge to a single solution, but I am not sure what that is. There has been very little work done on #1360 front and I am not sure how it will work out in the future.

Being devil's advocate, you could also argue that changing the `gazelle` plugin to ensure that `rules_pycross` integrates well with the `rules_python` gazelle plugin is a code smell. Creating a wrapper around `rules_pycross` hub repo, that would externally look like `rules_python` one is not too difficult (but tedious) if there is a known naming scheme. So doing that could be another workaround to consider.

**Comment by wingsofovnia** [comment]
> Creating a wrapper around rules_pycross hub repo, that would externally look like rules_python one is not too difficult (but tedious) if there is a known naming scheme. So doing that could be another workaround to consider.

There was an attempt here https://github.com/jvolkman/rules_pycross/pull/89. It gives some clues why the author decided not to accept it. Basically, it is inverse to your point that pycross ideas shouldn't be bend for the sake of satisfying another plugin.

> You could also argue that changing the gazelle plugin to ensure that rules_pycross integrates well with the rules_python gazelle plugin is a code smell.

I somewhat agree, but someone should make a first step unless the goal is to keep Gazelle plugin a closed garden I guess :) I'd say it should be the side where it gives a decoupling effect (Gazelle plugin) rather than an ugly bridge/adapter (rules_pycross).

Perhaps I see it is incorrectly, but `gazelle_python.yaml` to me is/should be just a lookup dict for Gazelle plugin. While I agree it is better to keep `modules_mapping ` as is, I'd see any target transformation/normalization happening on `gazelle_python.yaml` generation which the plugin should afterwards take as a 1:1 mapping and refrain from adding any configuration to alter runtime behaviour there. Gazelle directives sounds like a more common/appropriate place to alter Gazelle (incl. plugins) behaviour to me.

How about having a `target_convention` attr to `gazelle_python_manifest`? Something like:
```
gazelle_python_manifest(
    name = "requirements_mapping",
    modules_mapping = ":requirements_metadata",
    pip_repository_name = "pip",
    target_convention = "{{ printf "%s//:%s" $pip_repository_name (regexReplaceAll "[-._]+" (lower $target) "-") }}",
    requirements = ":requirements_txt",
)
```
with default value of `{{ printf "%s//%s" $pip_repository_name (regexReplaceAll "[_\\.]" (lower $target) $target "_") }}`. `pip_repository_name` attr might also be deprecated here to fully use `target_convention` while keeping backwards compatibility. `target_convention` can use [text/template](https://pkg.go.dev/text/template) with extra functions like `regexReplaceAll` from sprig, or it could be some custom simplified version of it.

**Comment by wingsofovnia** [comment]
What I was thinking w.r.t. `gazelle_python.yaml` is to keep it a simple mapping, rather than a using `gazelle_python.yaml` as a plugin configuration. I've suggested to put the config into `gazelle_python_manifest` rule, but in fact most plugins I've seen would probably use directives, including [Gazelle itself](https://github.com/bazelbuild/bazel-gazelle?tab=readme-ov-file#directives).

I like the idea of `normalization` enum. It could be:
* `none`
* `pep-503` - [normal Python names](https://peps.python.org/pep-0503/#normalized-names)
* `snake_case` - what `rules_python` does, default.

However, I would put it into a directive, rather than `gazelle_python.yaml`:
```
### rules_python
# gazelle:label_format $repo//$distribution
# gazelle:label_distribution_normalization snake_case

### rules_pycross
# gazelle:label_format $repo//:$distribution
# gazelle:label_distribution_normalization pep-503
```

No changes to `gazelle_python.yaml` needed. Backwards compatible and looks equally non-invasive. What do you think?

**Comment by aignas** [comment]
Sounds great! Keeping `gazelle_python.yaml` the same is even better.

**Comment by wingsofovnia** [comment]
`pep503` it is, @aignas :) I filed a PR #100, would be great to get your feedback!
