### ISSUE TITLE
Document how to create a python container image

### ISSUE THREAD

**Issue by blackliner** [bazelbuild/rules_python#2072]
# 🚀 feature request

### Description

Please show us how to get my `py_binary` plus it's dependencies, and of course a python interpreter/runtime (if not part of a base container layer) into a container image.

### Describe the solution you'd like

I would like my `py_binary` to be wrapped in a container image, including all it's dependecies

### Describe alternatives you've considered

It is 2024, and all the existing howtoos and tutorials are broken 😞 issues are closed without any relevant hint to a solution.
- https://github.com/bazelbuild/rules_python/issues/2055
- https://github.com/bazel-contrib/rules_oci/issues/55
- https://github.com/bazel-contrib/rules_oci/blob/main/docs/python.md --> broken (https://github.com/aspect-build/bazel-examples/tree/main/oci_python_image)

**Comment by aignas** [comment]
We don't own the `oci` examples, this is the base `rules_oci` ruleset. `py_binary` collects all of the runfiles and just adding it with `rules_oci` should just work.

At work I use the example from `rules_oci` and it is working for us, note that in order to build an image on a Mac that targets `linux_x86_64` you need to use the `experimental_index_url` attribute on `pip.parse` on bzlmod. The stabilization is tracked in #260.

Feel free to create a PR to the `oci_python_image` example you've linked. I'll close this issue as won't do.

**Comment by blackliner** [comment]
Hi @aignas , what example in `rules_oci` are you referring to?

**Comment by blackliner** [comment]
related: https://github.com/bazelbuild/rules_pkg/issues/803

**Comment by blackliner** [comment]
FYI, I managed to get it working, thanks for the hints on the runfiles etc.

```
filegroup(
    name = "params",
    srcs = ["params/params.json"],
)

py_binary(
    name = "app",
    srcs = ["app.py"],
    deps = [
        ":some_libs",
    ],
    data = [
        ":params",
    ],
)

pkg_tar(
    name = "app_tar",
    srcs = [":app"],
    include_runfiles = True,
)

oci_image(
    name = "app_image",
    base = "@python_base",
    cmd = ["/app"],
    workdir = "/app.runfiles/_main", # workaround for https://github.com/bazelbuild/rules_pkg/issues/813
    tars = [":app_tar"],
)
```

see also https://github.com/bazelbuild/rules_pkg/issues/813#issuecomment-2240806379

**Comment by aignas** [comment]
See here: https://github.com/bazel-contrib/rules_oci?tab=readme-ov-file#usage
