### ISSUE TITLE
bazel deps query with platform-specific pypi deps fails

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#2223]
# 🐞 bug report

### Affected Rule

Somethinng in the pypi integration

### Is this a regression?

Maybe? I used to be able to do `ibazel build //docs:docs` to have docs automatically
rebuilt while working on them. Now bazel gives an error during the query for deps ibazel
performs.

### Description

`bazel query 'deps(//docs:docs)` fails with an error. I think what's happening is a windows-specific dependency gets evaluated, which triggers a repo rule, and then wheel_installer fails.

## 🔬 Minimal Reproduction

Run `bazel query 'deps(//docs:docs)'`

## 🔥 Exception or Error

Full error: https://gist.github.com/rickeylev/d32a94e6823cb1541babc8565d88ccf8

I suspect the most relevant parts are
```
repo.execute: whl_library.BuildWheelFromSource(_main~pip_internal~dev_pip_311_colorama_sdist_08695f5c, colorama==0.4.6 ;sys_platform == 'win32'): ...
----
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
----
  File "/home/user/p/rickeylev/rules_python/python/private/pypi/whl_installer/wheel_installer.py", line 198, in main
    whl = Path(next(iter(glob.glob("*.whl"))))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

Hm, maybe the issue is wheel_installer isn't expecting an "empty" response? 

cc @aignas

**Comment by aignas** [comment]
I think there are a few things here:
* Bazel query will fetch the sdists, that you technically don't need for the build even if the wheels are available. It would be better to use cquery, but I am not sure it is possible to tell that to ibazel.
* We could trim the requirements line to not fail in this particular case though, it would only be a problem for platform specific distributions, but that is already a problem, so maybe that should be done here.

**Comment by aignas** [comment]
I see that there is a related issue here: https://github.com/bazelbuild/bazel-watcher/issues/594

**Comment by groodt** [comment]
A few more notes to add to @aignas commentary above:
* rules_python inherits the common, but unfortunate install-or-build-then-install behaviour of python packaging
* to remove the edge from `//docs:docs` to any sdist won't be easy

Some ideas (not sure on practicality): 
* ensure a wheel-only third party dependency graph
* move installation of wheels to build actions and repositories only reference archives (sdist or wheels)

**Comment by aignas** [comment]
I would love to go with 
> move installation of wheels to build actions and repositories _to_ only reference archive

But there are complications - we need to know the dependency graph before downloading the wheels and that is tricky. I was thinking about this for some time and the only way I can see it is to actually use @philsc's idea to introduce a custom lockfile format for `rules_python` (the implementation could be different here) so that the python toolchain is only used at `lock` time and during fetching we are only wiring everything up without any need for a python interpreter.

Right now python interpreter is used for:
* building from sdist - should be moved to a build action.
* patching the wheel - if we used `http_archive` this step would not be needed anymore.
* parsing the METADATA within the wheel - could be done at lock time in a build action.
* extracting the wheel - could be dropped and we could instead used an extracted `whl` or `sdist` (by using `http_archive`) and use build rules to lay them out correctly in the sandbox.

The implementation for all this could be:
* When running `uv lock` we also write a file named `rules_python.lock`, which would be a JSON file that the `pip.parse(experimental_index_url="foo")` understands. This could be just a JSON file with the parsed deps based on the target platforms.
* The `pip.parse(experimental_index_url="foo")` then would not need to query the PyPI index, because the `rules_python.lock` would have all of the information. Thus we could mark the extension as reproducible and the entries within the `MODULE.bazel.lock` would disappear, making the `rules_python.lock` the source of truth for what gets installed via the `pip` machinery.

Whilst this is a departure from
> a regular python lock file should just work with `rules_python`
I do think that this closes the main design issues we have right now that prevent us from stabilizing the feature in #260:
* We need to have a separate extension if we want to stabilize the new code.
* We need to have a Python interpreter during repo init time thus duplicating the toolchain selection logic. It works as long as the toolchains are unique per (os, arch) tuple, but if `musl` or `glibc` selection or #1876 comes into play, everything becomes tricky.
* We need to access the internet when evaluating the `bzlmod` extension - we should not need to. We should shift left and create the lock file when we are running `lock`.

I think we can come back to this topic once 1.0 is released and introduce it in a backwards compatible way over the next minor versions.

**Comment by rickeylev** [comment]
> to remove the edge from //docs:docs to any sdist won't be easy

Oh? Why? Did you see a particularly thorny one in the deps? I'd be +1 on moving it to a wheel-only build. Also, I thought there was a flag or something you could set to force things to be wheel-only?

If we put `platform=linux or platform=mac` in the requirements, will that work around the issue? For the docs building, we don't care about windows.

**Comment by rickeylev** [comment]
> building from sdist - should be moved to a build action.

Hm. What if we just moved it into a build action "as-is"? i.e. it's still only going to work when target == host, but that's fine; that's how it is today. But at least it's a build action and out of the repo phase. Which would probably avoid this bug? (it'd download the sdist, but not build anything)

> patching wheel, parsing metadata, extracting wheel

I just want to note that these don't require any toolchain-equivalent wiring. The interpreter the tools use isn't coupled to the processing they do. So we could, alternatively, simply hard-code particular interpreters to be used with our tools in the repo phase.
