### ISSUE TITLE
Status of rules_python

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_python#229]
Is this repository still Experimental / Alpha software?
Or do we recommend Bazel users to use it (instead of calling directly the native rules)?

It would be nice to clarify the documentation:
- https://github.com/bazelbuild/rules_python#experimental-bazel-python-rules
- https://docs.bazel.build/versions/master/be/python.html

**Comment by brandjon** [comment]
The packaging part is experimental, the core rules not so much. Will update this.

**Comment by laurentlb** [comment]
Thanks. I'd like to use https://github.com/bazelbuild/rules_python as the landing page for anyone using Python with Bazel.

**Comment by mdvorsky** [comment]
Hi @brandjon! It's good to hear that the intention is to keep maintaining this project. Does that mean we can look forward to getting more support in the near future? It's been really frustrating to see issues being open for many months without any response from maintainers whatsoever. (It's the lack of communication, rather than the lack of action that is particularly frustrating.) Thank you!
