### ISSUE TITLE
Removal of PyInfo from Bazel causes semantic change

### ISSUE THREAD

**Issue by comius** [bazelbuild/rules_python#2414]
# 🐞 bug report

### Description

I upgraded Bazel to use rules_python 0.39.0 -> all the tests pass.
I removed python providers from Bazel -> smoke tests started failing.

## 🔬 Minimal Reproduction

Checkout https://github.com/bazelbuild/bazel/pull/24343
bazel build //src/test/shell/bazel:bazel_example_test --test_filter=test_native_python

## 🔥 Exception or Error
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01932fe0-131a-4503-8eac-2516742f6f27/src/test/shell/bazel/bazel_example_test/shard_1_of_3/test_attempts/attempt_1.log

Example in: https://github.com/bazelbuild/bazel/blob/master/examples/py_native/bin.py

<pre><code>
-- Test log: -----------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_vczmqfyg/runfiles/_main/examples/py_native/bin.py", line 4, in <module>
    from fib import Fib
ModuleNotFoundError: No module named 'fib'
</code></pre>

# My thoughs

It looks like that part of information was in Builtin providers that now gets lost.

**Comment by rickeylev** [comment]
Just thinking out loud.
If fib isn't importable, then it would mean sys.path is different or the
file isn't present.
If PyInfo got lost, either is likely. Our test coverage for built-in PyInfo
interop is pretty light.
Otherwise, the other thing might be safe path (we enable it by default) --
it removes the main files dir from system.path, which the example is
relying on. The version of python used can affect this. That it varies by
bazel version makes me doubt this cause, though.

**Comment by rickeylev** [comment]
Ok, I think I figured it out. There's an operator precdence bug in collect_imports() that causes all imports strings to be dropped, but only if BuiltinPyInfo is none. I'll work on a fix.

**Comment by rickeylev** [comment]
According to the comments in https://github.com/bazelbuild/bazel/issues/24180, releasing a fix for this is a Bazel 8 blocker, so I'll prepare a release
