### ISSUE TITLE
Strip python files down to only application code

### ISSUE THREAD

**Issue by engnatha** [bazelbuild/rules_python#2453]
# 🚀 feature request

### Description

Curious if folks have discussed the idea of removing all supplementary code like comments/docstrings/etc when compiling py_binary and py_library targets. Naively thinking this could be done with a `genrule` in a macro that uses a tool like `sed` to strip away any comments. A benefit here would be that application code doesn't have to invalidate caches/test results when simple edits are made like fixing typos in comments or clarifying documentation. A more complete solution might use an abstract syntax tree parse of the file to more precisely determine what matters at run time and what doesn't.

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

An optional argument to these rules like `experimental_prune_code`.

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

Making a custom `genrule` to do this naively. [Precompiling](https://rules-python.readthedocs.io/en/latest/precompiling.html#precompiling) seems related to what I'm thinking of but still different.

 Have you considered any alternative solutions or workarounds?

**Comment by aignas** [comment]
Not sure if I am +1 on this idea:
* `noqa:` for linters is expressed as comments, so we have to allows for users to correctly handle this. `rules_lint` has aspects and rules that traverse `py_*` targets.
* stacktraces would become different because we would be stripping comments.

I think this is something that the user can do on their own if needed for niche cases, but doing this in the core rules seems risky and the benefits are small.

**Comment by rickeylev** [comment]
Yes, I agree with Ignas. This is niche.

This can be approximated by using pyc-only and, I think its optimize level 2. For something more advanced, a custom rule should be used to preprocess the sources before feeding them into `py_library.srcs`
