### ISSUE TITLE
[Bazel CI] Multiple failures in integration tests 


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#2469]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4313#01939501-8a44-41dc-a7b2-fb29fd9561d3

 Platform: Ubuntu

 Logs: 
```
FAIL: //tests/integration:compile_pip_requirements_workspace_test_bazel_self 
FAIL //tests/integration:ignore_root_user_error_workspace_test_bazel_self
FAIL //tests/integration:pip_parse_workspace_test_bazel_self
FAIL //tests/integration:py_cc_toolchain_registered_workspace_test_bazel_self
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_python
git reset 60da4a39e24381486d3d3bd089d516e3e0cad732  --hard
export USE_BAZEL_VERSION=3615f64a96f98efdb96ad48ed15cb0966d9961be
bazel test ... 
 ``` 
 CC Greenteam @wyverald

**Comment by rickeylev** [comment]
* rules_python (RBE)
`ERROR: While parsing option --toolchain_resolution_debug --remote_download_toplevel: Failed to build filter: value looks like another flag (--remote_download_toplevel). Either escape the value with "\-\-", or pass an explicit value to the flag.`

I don't think this is a rules_python issue? We just use the Bazel CI provided RBE configs.

* rules_python (default, windows)
  * //tests/bootstrap_impls:run_binary_zip_no_test -- `AssertionError: Cannot find .runfiles directory for c:\b\5bw2dcqy\execroot\_main\bazel-out\x64_windows-fastbuild\bin\tests\bootstrap_impls\run_binary_zip_no_test.exe.runfiles/_main/tests/bootstrap_impls/_run_binary_zip_no_test_bin
Test case failed: using no runfiles env vars`

No idea as to cause.

* rules_python (default, workspace) (mac, linux)
`rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined (did you mean 'CcInfo'?)` (same with PyRuntimeInfo)

I thought I had fixed this previously? Well, I'll have to look again.

* examples/pip_repository_annotations
* examples/py_proto_library
* examples/pip_parse_vendored
* examples/build_file_generation

ERROR: error loading package 'external': Both --enable_bzlmod and --enable_workspace are disabled, but one of them must be enabled to fetch external dependencies.`

I think this is because that example disable bzlmod, and with newer versions workspace must be explicitly enabled. Fix should be to modify its bazelrc to enable workspace.

* examples/multi_python_versions

`/rules_python/examples/multi_python_versions/tests/BUILD.bazel:162:8: in sh_test rule //tests:version_test_binary_3_8: label '//tests:version_3_8' in $(location) expression expands to more than one file, please use $(locations //tests:version_3_8) instead.  Files (at most 5 shown) are: [tests/_version_3_8.exe, tests/_version_3_8.zip, tests/version.py, tests/version_3_8.zip]`

I had to fix a similar error in another test. Fix is to switch to using `$(locations)`, then have the shell script parse out the appropriate entry. Long term, we need to change the rule behavior so that executables only produce 1 output, but that's a separate issue.

**Comment by rickeylev** [comment]
> rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined

Ok, this one is weird -- the version of rules_python being used, _in rules_python itself_, is version 0.28.0. Reproing this is easy: `USE_BAZEL_VERSION=last_green bazel build --nobuild ... --noenable_bzlmod --enable_workspace`

**Comment by rickeylev** [comment]
> //tests/bootstrap_impls:run_binary_zip_no_test fail to find runfiles on windows

This seems to be because `argv[0]` is different on bazel 9, namely, forward slashes aren't normalized to backslashes. What makes this weird is it doesn't seem to be Bazel doing this?

The test is a shell script that runs a python program. It looks like this:

```
bin=$(rlocation $RUNFILE_PATH)
$bin
```

Where `RUNFILE_PATH` is the result of `$(rootpaths)`, so it's a value like "foo/bar/baz". Thus, the result of `bin` is something like `c:\users\whatever\bazel-bin\test.runfiles/foo/bar/baz`. Note the mix of forward and backslashes.

On Bazel 7, when Python sees `sys.argv[0]`, it sees all backslashes. On Bazel 8, it sees the original string with a mixture of forward and backslashes.

Later in the bootstrap logic, a regex is looking for `.runfiles\` (a backslash, because windows). Since the actual string is `runfiles/` (forward slash), the regex fails to match, and eventually an error occurs. Normalizing it to the OS separator fixes the issue.

It's weird that changing the Bazel version seems to cause this. Everything else seems to be the same (Python version, bash version).

**Comment by rickeylev** [comment]
> rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined

I think I figured this out: defining the rules_python_internal repo was happening too late in the workspace processing. And then, i think bazel_tools ended up defining rules_python with an old version, somehow. In any case, defining rules_python_internal earlier seems to fix this. Another work around was to do `local_repository(name="rules_python", path = ".")`

**Comment by rickeylev** [comment]
> rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined

Ok, I give up trying to find a clean fix. Defining rules_python_internal helps, as did removing some unnecessary loads of bazel_tools in rules_python. However, I can't get past these errors with a nice fix:

```
ERROR: error loading package '@@bazel_tools//tools/jdk':
at /.../external/rules_python/python/defs.bzl:23:6:
at /.../external/rules_python/python/py_test.bzl:20:6:
at /.../external/rules_python/python/private/common/py_test_macro_bazel.bzl:17:6:
at /.../external/rules_python/python/private/common/py_test_rule_bazel.bzl:18:6:
at /.../external/rules_python/python/private/common/common.bzl:16:6: compilation of module 'python/private/reexports.bzl' failed
ERROR: /.../external/rules_java/toolchains/BUILD:356:27: error loading package '@@bazel_tools//tools/jdk':
at /.../external/rules_python/python/defs.bzl:23:6:
at /.../external/rules_python/python/py_test.bzl:20:6:
at /.../external/rules_python/python/private/common/py_test_macro_bazel.bzl:17:6:
at /.../external/rules_python/python/private/common/py_test_rule_bazel.bzl:18:6:
at /.../external/rules_python/python/private/common/common.bzl:16:6: compilation of module 'python/private/reexports.bzl' failed
  and referenced by '@@rules_java//toolchains:toolchain_java11_definition'
ERROR: /home/rlevasseur/p/rickeylev/rules_python/tests/pypi/whl_installer/BUILD.bazel:19:8: Analysis failed
```

Where `...` is /home/rlevasseur/.cache/bazel/_bazel_rlevasseur/f967450e3051c3f6e7591e325c574df5`

My best guess about that cause is a java toolchain in bazel_tools needs @bazel_tools//tools/jdk:BUILD, which loads rules_python, and then autoloading defines rules_python using rules_python 0.28.0.

I can't fix those loads, though, so I'll just use the local_repository() trick I mentioned before.

**Comment by rickeylev** [comment]
I think everything here is fixed. The issue with the flag added by bazel ci was fixed by https://github.com/bazelbuild/continuous-integration/pull/2141
