### ISSUE TITLE
manylinux2010 wheels do not seem to be used in pip3_import

### ISSUE THREAD

**Issue by gertvdijk** [bazelbuild/rules_python#276]
It seems that `pip3_import()` from `@rules_python//python:pip.bzl` does not recognize the wheels of type manylinux2010.

Example: `grpcio` 1.27.0 is now shipped without a manylinux1 wheel, but only manylinux2010 ([1.26.0](https://pypi.org/project/grpcio/1.26.0/#files) vs [1.27.0](https://pypi.org/project/grpcio/1.27.0/#files)). Ever since updating from 1.26.0 to 1.27.0 it now fails to use the wheel as a dependency and has to compile with abseil which takes a very long time.

I suspect the inability of rules_python to recognize the new wheel format as a wheel. I did a quick search on existing issues here, but I didn't see any - sorry if this has been reported already.

Relevant PR in grpc: https://github.com/grpc/grpc/pull/20282

**Comment by thundergolfer** [comment]
I think you need a `_manylinux.py` on your `PYTHONPATH` if you're on the Linux platform. Ours looks like: 

```python
print("Forcing _manylinux.py")
print("Forcing manylinux2010_compatible = True")
manylinux2010_compatible = True
```

**Comment by gertvdijk** [comment]
And 1.27.1 re-added manylinux1 support. :smile:

**Comment by groodt** [comment]
> I think you need a `_manylinux.py` on your `PYTHONPATH` if you're on the Linux platform. Ours looks like:

I wouldn't really call this reusable advice @thundergolfer This shim (a hack really) is only necessary on our environment at work and isn't really safe or recommended in general. It is up to Python distributors and installation tools to correctly register whether their distribution is manylinux{1|2010|2014} compatible. Then `pip` versions that support manylinux{1|2010|2014} will work correctly.

The complications around Bazel and `rules_python` for consuming third-party packages in this case, is that the vendored `pip` is old.

Using third-party Python packages from PyPI with Bazel isn't really safe or easy, which is why `pip_import` and `pip3_import` are considered unstable/experimental parts of `rules_python`. I almost wish they were removed, because they are misleading and do not work in general.

Using `pip` with Bazel is a mistake, but it is very convenient when it works. Incredibly frustrating when it doesn't work. 

The "best" way to support third-party Python packages with Bazel (from a purely technical point of view), is to vendor them (or external repository) and build from source (Bazel already supports this), but this is *a lot* of work and complex for packages with native code. Not to mention the burden of upgrading packages.

@gertvdijk If you're looking for more complete Bazel rules for Python PyPI packages have a look at the following:
https://github.com/dropbox/dbx_build_tools - Most complete, most complex. A lot more than just PyPI python packages though.
https://github.com/dillon-giacoppo/rules_python_external - Supports PyPI packages and transitive dependencies well. Lightweight.

Both are not perfect and suffer in general from the complexity and non-hermeticity of Python packages. i.e. if a Python source package setup.py requires native dependencies to be installed externally on a system, then you'll probably have issues. Luckily, this is rare, and most well packaged PyPI packages will work with the rules above.

There are also other rules worth looking at such as `rules_poetry` etc.
https://github.com/soniaai/rules_poetry

In general, Python package is complex and the hermeticity encouraged by Bazel highlights a number of areas where Python packaging is not particularly repeatable. Many people / companies end up with their own rules, wrappers, scripts etc to get things working for their particular build pipelines. Utilities like venv, Docker containers, Nix, preprocessing scripts etc. that can all be used to add dependencies to a system outside Bazel so that when impure tools like `pip` run, they are able to build. 

Normally once you've got it working for your use-case, it ends up being very specific, which is also part of the reason a general solution has not emerged. The good thing is, that once you've got it working smoothly enough for your use-case, it normally doesn't need that much ongoing maintenance, because Python packaging standards move slowly (thankfully) and the majority of Python packages are well packaged and simple to build, it's only esoteric or complex source packages with lots of native dependencies that might cause you headaches.
