### ISSUE TITLE
Is the dependency set in whl.py deterministic?

### ISSUE THREAD

**Issue by guillaumep** [bazelbuild/rules_python#289]
I might be wrong, but I'm wondering if the dependency_set declared here:
https://github.com/bazelbuild/rules_python/blob/94677401bc56ed5d756f50b441a6a5c7f735a6d4/packaging/whl.py#L86

and returned here:
https://github.com/bazelbuild/rules_python/blob/94677401bc56ed5d756f50b441a6a5c7f735a6d4/packaging/whl.py#L104

is deterministic or otherwise might introduce randomness in the build?

Should the return of the function be something like:

`return sorted(dependency_set)`

instead of `return dependency_set` ?

I did some tests using the Python 3 interpreter, and set() seems to retain the order of elements that were added to it, so this might not be an issue at all in reality. I prefer raising the question however, since this might just be an implementation detail of cpython and might not be a behaviour guaranteed in the future.

**Comment by thundergolfer** [comment]
I think because nothing is removed from the set, the CPython implementation will return them in deterministic insertion order. However to avoid relying on the implementation instead of the interface, in [`rules_python_external` we sort the set](https://github.com/dillon-giacoppo/rules_python_external/blob/a6c756df528d4e6034a9f5ddebfe297910134092/extract_wheels/lib/bazel.py#L140). 

Sorting the set also has the added minor benefit of not creating `BUILD` files which Bazel's file formatter (`buildifier`) considers wrong.

**Comment by andyscott** [comment]
This should be fixed now
