### ISSUE TITLE
Find replacement for Transition cache

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_python#298]
`PythonVersionTransition.java` currently has a cache. If we ever want to migrate to Starlark, we need a replacement.

**Comment by brandjon** [comment]
(xref #297)

I'm not sure what cache you mean, but in general, to migrate to Starlark we'll have to express the Python version transition as a Starlark-defined transition. I've prototyped this in the past but stopped short of uploading it here as a utility because it changes the output directory path, which messes up unshareable actions (C++ actions in particular).
