### ISSUE TITLE
pip dependencies aren't available if main target is a sh_binary

### ISSUE THREAD

**Issue by chasain** [bazelbuild/rules_python#313]
We use a set of services built in python that we coordinate together with shell scripts. When we moved to declaring the requirements as data dependencies of our python targets we discovered they aren't available when we run our main target. We're using version 0.0.2

**What doesn't work:**
```
load("@py_pip_deps//:requirements.bzl", "requirement")

sh_binary(
    name = "pyservice",
    srcs = ["run_service.sh"],
    data = [
        ":server",
    ],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    data = [
        requirement("protobuf"),
        requirement("grpcio"),
    ],
)
```

**What does work:**

```
py_binary(
    name = "pyservice",
    srcs = ["run_service.py"],
    data = [
        ":server",
    ],
)
py_binary(
    name = "server",
...
```

**Comment by fahhem** [comment]
they should be under `deps`, why are you using `data`? In the bazel docks, they claim they're similar, but the purpose of `deps` is "build-time" and `data` is "run-time", and since there is no actual build-time for Python the docs say they're irrelevant. I wouldn't be surprised if there are other downstream effects of going with `data` over `deps`

**Comment by thundergolfer** [comment]
In order to better deal with this potential issue it would be good to get a full reproduction. I'd be particularly interested in exactly what the `run_service.sh` is doing to discover and invoke the `:server`. 

Also, like @fahhem points out, having the package dependencies in the `py_binary.data` attribute is strange: 

```
    data = [
        requirement("protobuf"),
        requirement("grpcio"),
    ],
```
