### ISSUE TITLE
How should I download en_core_web_sm using Bazel?

### ISSUE THREAD

**Issue by sophieball** [bazelbuild/rules_python#324]
My program needs to use spacy's en_core_web_sm model. Usually I need to run it with `python -m spacy download en`, but that does not download it to Bazel's directories. 

I have succeed by adding the url of the model to my `requirements.txt`. 

I was wondering if there's a way that I can do it in `WORKSPACE` or `BUILD` file?

**Comment by thundergolfer** [comment]
We've dealt with this exact same issue at work at some point, and we opted to manage the download in our code.

> I have succeed by adding the url of the model to my requirements.txt.

Interesting I just looked this up and landed on https://spacy.io/usage/models#models-download. 

The above works because the model is a valid python package. The way these rules support external packages is via `requirement()`. How would you want this to work in a `WORKSPACE` or `BUILD` file?

**Comment by sophieball** [comment]
Oh, downloading it in the code makes sense! Thanks.

**Comment by thundergolfer** [comment]
No worries at all. I'll close the issue. Let me know if if there's any more to discuss.
