### ISSUE TITLE
Update setuptools to current (54.0)

### ISSUE THREAD

**Issue by phlax** [bazelbuild/rules_python#421]
# 🚀 feature request (+ ~bug)

### Relevant Rules

Setup tools install

### Description

Currently the setuptools version is 42.x this appears to have problems with building wheels in windows

for ref - see https://github.com/envoyproxy/envoy/pull/15236#issuecomment-788050782 for PR which hit this windows problem

### Describe the solution you'd like

Update to current (54.0) or at least > 51.0 as this seems to fix the problem we have had

I would be happy to raise a PR to fix if there is interest to update

### Describe alternatives you've considered

we are patching rules_python to update setuptools

**Comment by groodt** [comment]
Can you try again from master instead of the release tag? The release tag is ancient.

Long shot, but it might help since this PR did bump things a little:
https://github.com/bazelbuild/rules_python/pull/390
(setuptools 44.1.0)

There is a bit of queue of PRs that tasks that I think we're waiting for:
* Maintainers to cut new release that will be the last release with any semblance of Python 2.7 and 3.5 support for `pip_install` (it was never really supported, but kinda worked sometimes).
* Remove Python 3.5 support from CI https://github.com/bazelbuild/rules_python/pull/417
* Upgrade to pip 21.0.1 (pip dropping Python 2.7 and this adds support for Big Sur and Apple Silicon wheels. The setuptools upgrade could possibly be added here tbh, since setuptools > 45 requires Python > 3.5.

**Comment by phlax** [comment]
> Can you try again from master instead of the release tag? The release tag is ancient.

I thnk master still points to the old setuptools version:

https://github.com/bazelbuild/rules_python/blob/c639955c18bbc16e6a9e5228540b6151fd3b10b3/python/requirements.txt#L2

and here

https://github.com/bazelbuild/rules_python/blob/c7e068d38e2fec1d899e1c150e372f205c220e27/python/pip_install/repositories.bzl#L19

**Comment by phlax** [comment]
ah wait - i see that is 44.0 not 42 - ill try again to see if that fixes the problem i had

**Comment by phlax** [comment]
@groodt seem like the problem remains in setuptools 44.1.0

for ref the failing ci can be seen here https://dev.azure.com/cncf/envoy/_build/results?buildId=67847&view=logs&j=959800d2-504c-5424-ae5b-beaf4b89831b&t=5012f2a4-f1a0-5822-b3e6-7b2c1f819b7c&l=3382

ill open a PR to bump the version...

**Comment by hrfuller** [comment]
closed by #422
