### ISSUE TITLE
Replace `subpar` with a cross-platform solution

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_python#436]
# 🚀 feature request

### Description

 A clear and concise description of the problem or missing capability...

I opened this as a feature request because I otherwise didn't know how to raise open the issue

Right now the rules use [subpar](https://github.com/google/subpar) to generate some executable which are then committed back and reused for other rules:
https://github.com/bazelbuild/rules_python/blob/c37ba2215eccab53ae1da5f827a335281f81b9e1/packaging/BUILD#L45-L62

Is there a reason these couldn't be converted to using Bazel's `python_zip_file` functionality to accomplish the same thing? (introduced in https://github.com/bazelbuild/bazel/pull/9453)

**Comment by UebelAndre** [comment]
If this is possible, would it solve for the outstanding issue on https://github.com/bazelbuild/rules_python/pull/344

**Comment by UebelAndre** [comment]
is the generated zip (zipapp? [PEP-0441](https://www.python.org/dev/peps/pep-0441/)) cross platform? Does anyone know it's limitations there? I'm pretty surprised this is not a more advertised feature.

**Comment by hrfuller** [comment]
The zipapp won't be cross-platform. Any rules_python pip dependencies are fetched only for the local platform. In some cases with universal wheels they *could* be cross-platform, but it isn't a guarantee.

**Comment by UebelAndre** [comment]
Is there currently a cross platform implementation for self contained Python apps?

**Comment by bshashank** [comment]
> The .zip won't be cross-platform. Any rules_python pip dependencies are fetched only for the local platform. In some cases with universal wheels they could be cross-platform, but it isn't a guarantee. Having said that and without in depth knowledge I don't think subpar's are truly cross-platform either.

I agree, subpar and `--build_python_zip` behave in a similar manner wrt cross-platform. The one advantage of subpar is that you can ask for the par to be unzipped before execution - which helps Python discover compiled code (`.so` or `.dlls`) more easily.

Since pip and wheel are both pure-python, I think both subpar and `--build_python_zip` would work in the same manner.

**Comment by UebelAndre** [comment]
Except in that the zips are producible on windows and the pars are not, right?

**Comment by hrfuller** [comment]
FWIW if cross-platform support is a necessity, which it may not be here, https://github.com/pantsbuild/pex has cross-platform support.

**Comment by UebelAndre** [comment]
Nice! Are there Bazel rules for that?

Also, do all Python rules currently work on all platforms? I thought the par files were a bottleneck for windows

**Comment by shridevinb** [comment]
I need to build .par files on windows. is there a workaround for it apart from using --build_python_zip?

**Comment by UebelAndre** [comment]
For what it's worth, I found [@apache_incubator_heron//tools/rules/pex](https://github.com/apache/incubator-heron/tree/3215a7603d05342c635bdfbdfdc009d10c61ab37/tools/rules/pex) which seems to be a fork of https://github.com/benley/bazel_rules_pex at first glance but perhaps those rules can be used to finally address https://github.com/bazelbuild/rules_python/issues/2 ?

**Comment by UebelAndre** [comment]
I also came across https://github.com/arrdem/rules_zapp which seems like it might solve for some of the needs here.

**Comment by groodt** [comment]
The two `.par` files in the repo are only used to support the legacy `pip_import` mechanism https://github.com/bazelbuild/rules_python#importing-pip-dependencies-with-pip_import-legacy

Maybe @brandjon or other maintainers can confirm if this can be dropped in the next release and then the need for the `subpar` dependency is removed.

If not, the `.par` files used as part of `rules_python` only take a dependency on pure Python wheels.

[See here.](https://github.com/bazelbuild/rules_python/blob/9a10fdb84911aad767acb60b603c62108f3228f4/packaging/BUILD#L45-L62)
```
        requirement("pip"),
        requirement("wheel"),
```

The `.par` files could be replaced by `--build_python_zip`. No additional dependencies would be required. It would work cross-platform because these dependencies are pure Python. Note: it would *NOT* make all the rules automatically cross-platform. It would only make the rules "execute" on Windows, which is a step forward I guess.

If I recall correctly, the shebang in a zip from `--build_python_zip` is `#!/usr/bin/env python`, which is supported on POSIX and also the Windows Python launcher. Of course, be careful of Python2 vs Python 3 on the PATH.

This does of course require Python to be installed on the PATH of the host and is not hermetic / toolchain aware, but this is true of the current situation with `subpar` as well as far as I understand.

This is why I think the easiest path forward is to remove the legacy `pip_import` mechanism.

**Comment by alexeagle** [comment]
@thundergolfer @hrfuller feels to me like we are nearly two years past EOL for Python 2 and dropping some tech debt from rules_python would benefit us, so I'd like to adopt @groodt proposal here to remove the legacy `pip_import` along with anything which exists only to support it. Losing all `.par` files and the machinery to produce them seems totally worth the tradeoff for users who will get stuck on an older rules_python.
WDYT?

**Comment by UebelAndre** [comment]
If it helps any, dropping the legacy code would make investigations and feature development easier. I've gotten myself confused as to why I don't see the behavior or code I expect only to find i'm looking at the wrong file but didn't notice because it's so similar.

**Comment by hrfuller** [comment]
@alexeagle I agree its time to ditch them. We should work on some rudimentary pex rules to replace par in the future.

**Comment by UebelAndre** [comment]
Since the use of [subpar](https://github.com/google/subpar) was removed in https://github.com/bazelbuild/rules_python/pull/582, there's no longer a need for a cross-platform solution. Closing this issue out as a result.

**Comment by alexeagle** [comment]
Thanks Andre!
