### ISSUE TITLE
Proper (cross) compilation of pip packages

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/rules_python#453]
# 🚀 feature request

I want to use pip packages that require compilation to install. I'd also like to use Bazel's platform transitions and a hermetic cross-compilation toolchain to easily build pip packages for any (linux) target.<sup>[1](#bazel-sig-cc)</sup>

### Relevant Rules

`pip_parse`

### Describe the solution you'd like

I expect we'd need to adjust `pip_parse` logic to do wheel extraction (or compilation) during Bazel's execution phase.

If we can switch `pip_parse` to generate `BUILD` files that do the wheel extraction / pip install in a `genrule` or other non-repository rule, then we can use the toolchain Bazel has selected for the target platform. Note that in the non-cross-compilation case this would just be the host platform cc toolchain.

There are two ways to get access to the current cc toolchain:
- a `genrule` and a command that uses the make variables `CC` and `CC_FLAGS` to run the pip command (see https://docs.bazel.build/versions/master/be/make-variables.html#custom_variables).
- a custom rule, reading these flag values directly from the current toolchain provider and set the environment for the associated execute action.

### Describe alternatives you've considered

- Leave package installation / compilation in Bazel's loading phase and use repository rules workarounds to find and set `CC` and `CFLAGS`. This is feasible but slower (since repository rules do not benefit from fine-grained parallelism), harder to maintain, and kind of a mess.

- Can also continue with the status quo of manually porting non-wheel-based pip packages over to build with Bazel. This is very challenging, time consuming, and error prone. Doubly so in the context of cross compilation.

<a name="bazel-zig-cc">1</a>: I have been building a hermetic cross-compilation toolchain for Bazel that's relatively small and straightforward to use. It patches rules_docker to use platform transitions for targets that are used inside the `cc_image`. Here's a preview: https://github.com/ajbouh/bazel-zig-cc.

**Comment by groodt** [comment]
If you've not seen them already, the [dbx_build_tools](https://github.com/dropbox/dbx_build_tools) rules from Dropbox are currently the most sophisticated in terms of building third-party Python code from source using toolchains registered with Bazel. Python also often requires Fortran to be setup if I recall for many of the Numerical / Scientific libraries, but the Dropbox rules should make this clearer.

When you talk about "cross-compilation", are you talking about cross-compilation in across CPU architectures (x86 vs ARM etc) or also across OS (win, macos, linux)? The reason I ask is because something that should be considered is that it is relatively common to come across "platform specific" dependencies. [PEP 508](https://www.python.org/dev/peps/pep-0508/#id24) defines so called "Environment Markers" that change the dependency graph based on the system where the installation is happening. One example from Jupyter is https://github.com/ipython/ipython/blob/master/setup.py#L212.

Python does not currently have strictly separate resolve, build, install steps. It is the "resolve + build" step that is currently coupled, but Python is taking some steps towards making as much of this "static" as possible. However, in the vast majority of cases, `setup.py` still needs to execute and this is dynamic behavior. Perhaps a workaround for this would be to run the "resolve" step for all desired target platforms and somehow `select` the appropriate dependency graph at Bazel build time.

**Comment by ajbouh** [comment]
> If you've not seen them already, the [dbx_build_tools](https://github.com/dropbox/dbx_build_tools) rules from Dropbox are currently the most sophisticated in terms of building third-party Python code from source using toolchains registered with Bazel. Python also often requires Fortran to be setup if I recall for many of the Numerical / Scientific libraries, but the Dropbox rules should make this clearer.

Thanks, I've recently become aware of them but have not yet explored what they're capable of. Thanks for the pointer re: Fortran.

> When you talk about "cross-compilation", are you talking about cross-compilation across CPU architectures (x86 vs ARM etc) or also across OS (win, macos, linux)? The reason I ask is because something that should be considered is that it is relatively common to come across "platform specific" dependencies. [PEP 508](https://www.python.org/dev/peps/pep-0508/#id24) defines so called "Environment Markers" that change the dependency graph based on the system where the installation is happening. One example from Jupyter is https://github.com/ipython/ipython/blob/master/setup.py#L212.

I mean cross OS and cross architecture. For now I'm installing pre-compiled wheels by specifying a number of additional pip arguments:
```
  "--only-binary", ":all",
  "--platform=manylinux2014_x86_64",
  "--platform=manylinux2010_x86_64",
```

> Python does not currently have strictly separate resolve, build, install steps. It is the "resolve + build" step that is currently coupled, but Python is taking some steps towards making as much of this "static" as possible. However, in the vast majority of cases, `setup.py` still needs to execute and this is dynamic behavior. Perhaps a workaround for this would be to run the "resolve" step for all desired target platforms and somehow `select` the appropriate dependency graph at Bazel build time.

Right now I work around this by specifying different pip repositories for each platform and then a sort of "meta" `requirement` macro that looks like this:
```
load("@pypi_manylinux2010_x86_64//:requirements.bzl", linux_requirement = "requirement")
load("@pypi_macosx_x86_64//:requirements.bzl", darwin_requirement = "requirement")

def requirement(name):
  return select({
    "@platforms//os:linux": [linux_requirement(name)],
    "@platforms//os:macos": [darwin_requirement(name)],
    "//conditions:default": [],
  })
```

My approach seems to work fine for precompiled wheels, but I'm now seeing the need to extend rules_python so that it works for packages that require compilation.

**Comment by groodt** [comment]
The Python packaging ecosystem is always evolving, so in some sense it might be wise to take a "wait and see" approach until things have stabilised. Of course, things may never settle. :)

For example, there is an evolving standard in [PEP-517](https://www.python.org/dev/peps/pep-0517/). This clarifies the responsibilities of the so called "build front-end" and "build back-end". 

Any "package author" is able to define and configure how their package builds from the package's source tree through their "build back-end", but package "end-users" are responsible for selecting and configuring the "build front-end".

It might be possible someday for Bazel rules_python to become a compliant PEP-517 "build front-end" if this standard is accepted and the ecosystem accepts it. However, what does that then mean if a package author wishes to use `flit` or other tools to build the wheel, instead of `pip`? Interesting times ahead I think.

> My approach seems to work fine for precompiled wheels, but I'm now seeing the need to extend rules_python so that it works for packages that require compilation.

Not sure if you've considered it, but another option for your use case, if they are always third-party dependencies you are looking to precompile would be to build the wheels for your target platforms and host the artifacts in your own mirror (artifactory etc). Then Bazel can always work against prebuilt wheels which it simply needs to download and unpack.

**Comment by thundergolfer** [comment]
Related issue: https://github.com/bazelbuild/rules_python/issues/260 ("Cross compilation" of py_binary/py_image/py_library targets)
