### ISSUE TITLE
Python code formatting rule

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_python#509]
# 🚀 feature request

### Relevant Rules

This feature request is for a new rule.

### Description

 A clear and concise description of the problem or missing capability...
I'm looking for a rule I can use to format python code and enforce formatting (likely via an [aspect](https://docs.bazel.build/versions/main/skylark/aspects.html)).

It'd be great if this rule was configurable and worked with (at least):
- [black](https://github.com/psf/black)
- [autopep8](https://github.com/hhatto/autopep8)
- [yapf](https://github.com/google/yapf)

There's a similar [rule in `rules_rust`](https://bazelbuild.github.io/rules_rust/rust_fmt.html#setup) for `rustfmt` where formatting can be enforced via an aspect and applied via a runtime rule which I've found to be very impactful. A python rule would be fantastic.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?
There's likely an existing rule in someone's personal repository for this but I'm looking for something that can be promoted to live in `rules_python` directly. Rules in `rules_rust` have more visibility, particularly if they're communicated in the [release notes](https://github.com/bazelbuild/rules_python/releases). I'm willing to try out a 3rd party solution but only if there's a path to up-streaming that solution.

**Comment by arrdem** [comment]
I was able to knock out a prototype of flake8 using this aspects model, the aspects docs and the rules_rust examples. Not ideal at all but workable. https://github.com/arrdem/source/blob/trunk/tools/flake8/flake8.bzl

**Comment by UebelAndre** [comment]
This functionality is still very much desired.

**Comment by adam-azarchs** [comment]
At our company I built a macro that generates a python unit test which runs `black --check`, `pyflakes`, and `pylint`, and then declares a `py_test` target for it. In hindsight, I probably should have just had it run `flake8` with plugins for the others, but live and learn.  For a simpler approach, you can have a macro run a genrule to format the source file, and then use a `diff_test` (from skylib) to check the result.

At any rate, I think that approach (having individual test targets) is generally more idiomatic than having one target which globs up all of your sources and tests them all at once.  On the other hand, then you need a way to enforce that those rules are applied to new source files.

**Comment by UebelAndre** [comment]
This is still desirable

**Comment by aignas** [comment]
I would be interested in this functionality as well.

**Comment by adam-azarchs** [comment]
Maybe we'll have bandwidth to open-source our rule set at some point, but in the mean time, this is really not that hard.  You can use a macro with [`write_file`](https://github.com/bazelbuild/bazel-skylib/blob/main/docs/write_file_doc.md) to write a little script, for example
```python
import unittest
from black import main as _black_main


class TestFormat(unittest.TestCase):
    def test_black(self):
        _black_main(
            [
                "--color",
                "--check",{}
                r"{}",
            ]
        )


if __name__ == "__main__":
    unittest.main(buffer=True, verbosity=0)
```
subbing in the `--config=` if applicable and the list of paths to check, and then make a `py_test` out of that.  If you want to be able to pass in `py_{library,test,binary}` targets in addition to passing the sources directly then you need a rule rather than `write_file` for the first bit but it's still not hard.

**Comment by aignas** [comment]
We have our internal rule as well, but looking at the `rustfmt` [source](https://github.com/bazelbuild/rules_rust/blob/main/rust/private/rustfmt.bzl) I see that it is much more solid. Our current approach is a custom `_test` rule for python formatting that is running both, `black` and `isort` at the same time.

**Comment by adam-azarchs** [comment]
Ours also runs `pyflakes` and `pylint`, and also imports the module as a basic sanity check of the dependency declarations.  Maybe a bit much to dump into a single test target?  But on the other hand we have a lot of python files and I run out of inodes from all of the runfiles symlink forests if we break them up into too many separate targets...

I also use [absltest.main()](https://abseil.io/docs/python/guides/testing) rather than `unittest.main()` as a lightweight way to get those individual check results to get properly wrapped up in junit xml for cleaner output.

**Comment by ramilmsh** [comment]
+1

**Comment by alexeagle** [comment]
https://github.com/aspect-build/bazel-super-formatter may be interesting to anyone following this thread, it uses Bazel to create a formatter that runs Black on Python code, and also formats most other languages using their idiomatic formatter tool. It doesn't require any changes in BUILD files.

**Comment by alexeagle** [comment]
Update: aspect-build/rules_lint uses super fast Ruff for formatting.

**Comment by arrdem** [comment]
Stale bots are a plague on this industry.

**Comment by adam-azarchs** [comment]
I don't think this isn't going to happen, for the same reason as https://github.com/bazelbuild/rules_python/pull/723#issuecomment-1307664330
`rules_python` is test-framework-agnostic, it's also going to be linter/formatter agnostic.  This repo is for the basic, universal functionality for python rules.  Framework-specific rules (which would include rules for any given specific formatter) belong in a separate repo.  Or at least that's the decision referenced in that comment.
