### ISSUE TITLE
Update documentation for utilizing py_library from nested folder

### ISSUE THREAD

**Issue by PranavSathy** [bazelbuild/rules_python#54]
Hi Everyone,

My current folder structure is as follows:

```
WORKSPACE
analysis/
analysis/analysis.py
analysis/BUILD
analysis/analyzers/average.py
analysis/analyzers/BUILD
```

I am trying to import all the analyzers in my `analysis.py` file, and the two BUILD rules look as follows:

```
py_binary(
    name = "analysis",
    srcs = ["analysis.py"],
    deps = [
      "//analysis/analyzers",
      requirement("pandas"),
      requirement("plotly"),
    ],
)
```

```
py_library(
    name = "analyzers",
    srcs = ["average.py"],
    deps = [
       requirement("pandas"),
    ],
)
```

It seems like I have tried every way of attempting to import `analyzers` into my `analysis.py` file, including;

```
import analyzers
import analysis.analyzers
from analysis import analyzers
from analysis.analyzers import analyzers
from analysis.analyzers import average
```

along with those combinations with my WORKSPACE name.

Am I missing something obvious? thanks!

**Comment by PranavSathy** [comment]
Ok, I figured it out, it seems that because the name of my py_binary is `analysis` as well as the name of the file `analysis.py`, the import statement in the file could not find the submodules (folders) within because it seems to have been interpretting the actual analysis.py file.

If I simple do `import analysis` in my `analysis.py` file, it actually executes twice.

Is there some rationale as to why py_binary/py_library do this? I can escalate this into the actual bazelbuild/bazel repo since this is behavior exhibited by the native rules.

**Comment by mattmoor** [comment]
@ulfjack Who owns the native Python rules?

**Comment by ulfjack** [comment]
lberki does, although we're planning on transitioning them to the python team this year. @duggelz

**Comment by duggelz** [comment]
My practical advice is to rename the directory or the source file.  Yes, we should handle this, but you'll keep running into similar problems down the line, due to the way Python works.

This should be fixed once this change is released in Bazel: https://github.com/bazelbuild/bazel/commit/e9c885a88137fa10ea0ac95ff33dcfdc79c6cf0a

You'll need to add `legacy_create_init=false` to your `py_binary` and `py_library` targets.

Meanwhile, my practical advice is to rename the directory or the file.  You'll keep running into similar problems, even in non-Bazel contexts, because of how Python implicitly adds the main script directory to the start of the Python import path.

**Comment by brandjon** [comment]
Regarding the Python behavior of adding the main script's directory to the import path, this is something we'd like to workaround to eliminate a class of hermeticity problems. See bazelbuild/bazel#7091.
