### ISSUE TITLE
patch a `pip_install`

### ISSUE THREAD

**Issue by knzivid** [bazelbuild/rules_python#553]
# 🚀 feature request

### Relevant Rules

`pip_install`

### Description

I want to patch a python package after it is installed. 

### Describe the solution you'd like

Similar to `patches` argument in [`http_archive`](https://docs.bazel.build/versions/main/repo/http.html#http_archive-patches), I would like an extra argument in `pip_install`. 

### Describe alternatives you've considered

- `extra_pip_args` argument - I did not find a way to request `pip` to patch a package
- Forking upstream with my tiny patch - I am open to workarounds but this is my last resort

### Potential problems

- `pyc` files will be invalidated

**Comment by UebelAndre** [comment]
I've been able to modify the `package_annotation` functionality (from https://github.com/bazelbuild/rules_python/pull/589) to add some patching support to `whl_library` but the patching applies after the wheel is installed. I think it'd be ideal to patch before but I'm not sure how to go about setting up an extracted wheel. Any suggestions or opinions there?

**Comment by philsc** [comment]
@UebelAndre , do you have a PR for your wheel patches via annotations? If not, I have an internal patch that I can clean up and put up a PR.  My internal patch also works with annotations post build.  I don't know how one would implement pre-build patches because it would require intercepting `pip`.  Also, we don't have any use cases for it at the moment.

**Comment by UebelAndre** [comment]
> @UebelAndre , do you have a PR for your wheel patches via annotations? I

I do not, I was able to use the new `download_only` feature with custom built wheels to remove the need for patching.

**Comment by creste** [comment]
> I have an internal patch that I can clean up and put up a PR. My internal patch also works with annotations post build.

@philsc - That would be very helpful for me.  I am also interested in patching python packages after they are built.

**Comment by philsc** [comment]
@creste , apologies for the delay. Here are the "non-cleaned-up" patches: https://github.com/frc971/971-Robot-Code/tree/master/third_party/rules_python
These patches (specifically, the second one) allow you to create a file like this: https://github.com/frc971/971-Robot-Code/blob/master/tools/python/patches.json
There you can specify the patches you care about.
You can point the WORKSPACE at the patches.json file like this: https://github.com/frc971/971-Robot-Code/blob/3eaca7e070c0b4a6909eaf6eec14ac26e5364dce/WORKSPACE#L441

It's not ideal, but this works for us at the moment.

I ended up abandoning the annotations approach because @groodt convinced me to avoid adding more annotations features. Instead, I am working on a proposal for a different approach. I am finding less time for that proposal than I was hoping so I don't have anything to show you, unfortunately.

**Comment by creste** [comment]
@philsc - Thank you! That is extremely helpful!

**Comment by Topher-the-Geek** [comment]
The patches above are for python_rules v0.16.1. There's been significant changes to the wheel installer since then. I think there's an easier way to go about this, especially if the source for the package is open on GitHub.

1. Fork the source of the package
2. Make your changes
3. In requirements.txt, write something like `git+https://github.com/<you or your org>/<your repo>@<your tag or hash>`

You're probably going to do the first 2 steps anyways to submit a PR to the source.

**Comment by lazcamus** [comment]
forward ported patch: [patch_wheels_0.26.0.patch](https://github.com/bazelbuild/rules_python/files/13179718/patch_wheels_0.26.0.patch)

**Comment by aignas** [comment]
Support of wheel patching should work on `bzlmod` now with `0.27.0`: https://github.com/bazelbuild/bazel-central-registry/pull/1138

**Comment by aignas** [comment]
I think that #914 is about the same feature and https://github.com/bazelbuild/rules_python/issues/914#issuecomment-1857178068 contains pointers of how one would use the patching machinery in `WORKSPACE`.

**Comment by aignas** [comment]
Since `bzlmod` is becoming the standard, I'll close this issue since the patching support is here.

**Comment by nikonikolov** [comment]
@aignas I am not a bazel pro and I am struggling to setup a patch in the legacy WORKSPACE structure. Could you provide an example? Last I tried, I remember `rules_python` didn't yet fully work with bzlmod so I couldn't migrate yet.

**Comment by aignas** [comment]
Whilst some bzlmod APIs may still change nearing 1.0, it has greatly matured, so feel free to give it a try. If you are having issues, please create new issues.

**Comment by nikonikolov** [comment]
That's good to hear, I will give it a try as soon as I can, but transition will definitely take non-trivial time and I am in a big rush to get some other things done, so an example would be really helpful so I can do a quick fix and move on. Thanks!
