### ISSUE TITLE
Missing "archive" asset in GitHub for the 0.6.0 release

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/rules_python#607]
In each of the previous releases (from `0.0.1` to `0.5.0`), the release assets included an "archive" following the following URL pattern: `https://github.com/bazelbuild/rules_python/releases/download/<version>/rules_python-<version>.tar.gz`.

It presents itself like the first item below:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/57383/150819540-5cbddb70-64cf-4fdd-b3c8-658f01c4b566.png">

Unfortunately this item is missing on the latest 0.6.0 release:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/57383/150820603-7300269e-c8c6-4e0d-b496-0619e19256e6.png">

This may break users' automated repository update script which assume that the current repository url (`https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz`) can be updated to `https://github.com/bazelbuild/rules_python/releases/download/0.6.0/rules_python-0.6.0.tar.gz`.

I am not 100% sure what the release process involves for this repository but I know that an archive can be added manually by uploading the relevant tarball during release creation/edition:

![image](https://user-images.githubusercontent.com/57383/150821062-8ea1db5d-f43a-4590-af26-09961fb847e6.png)

**Comment by thundergolfer** [comment]
cc @alexeagle is this related to the release issue you mentioned last week?

**Comment by alexeagle** [comment]
There is no longer an archive asset published. As of rules_python 0.6.0 the release instructions have changed the URL format to use the archive produced by GitHub. You'll have to update the assumptions in your automated repository update script.

(Note that GH archives are much more common in bazel rulesets than uploaded assets, so our previous setup was the oddball. We needed that because we had some massive files checked into the repo which necessitated publishing an asset containing only a subset of the repo, but it make our release mechanics more complex. You can check the PR for more https://github.com/bazelbuild/rules_python/pull/587 )

**Comment by sitaktif** [comment]
Sounds good, thanks for the info 👍
