### ISSUE TITLE
wheel installations

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/rules_python#69]
I want to use a .whl file dependency. How can I do this with rules_python. I can't find any way to do this in the documentation.

**Comment by clintharrison** [comment]
There is an internal `whl_library` rule, but this is not meant to be used on its own. The `pip_import` rule should be used.

**Comment by solomatov** [comment]
@clintharrison Are there any plans to support virtualenvs? AFAIU, in order to use them for development, I need to run bazel inside of virtualenv.

**Comment by mattmoor** [comment]
@duggelz This feels like it would be a fantastic extension of the nascent `py_runtime` stuff.

**Comment by combacsa** [comment]
Hello. Also waiting for this feature here. pip_import doesn't seem to support whl file installation as of now.

I'd like to put some .whl files under my workspace(since they're not provided by pypi yet) and let it be installed. Tried to write down the name of .whl file in "requirements.txt" but it tries to look into the bazel external folder instead of the workspace folder(somewhere nearby repository root)...

**Comment by combacsa** [comment]
I have no idea why suddenly assignees are changed by me. If it's my mistake, sorry about that. Don't know how to undo it.

**Comment by thundergolfer** [comment]
`whl_library` supports downloading and using a single `.whl` file. `py_import` supports only `.egg` format, but [accepts contributions on adding `.whl` support.](https://github.com/bazelbuild/rules_python/blob/aef17ad72919d184e5edb7abf61509eb78e57eda/python/defs.bzl#L161)

Ref: https://github.com/bazelbuild/rules_python/blob/main/docs/pip_repository.md#whl_library
