### ISSUE TITLE
`pip_install` other dependencies

### ISSUE THREAD

**Issue by sschaetz** [bazelbuild/rules_python#819]
# 🚀 feature request

### Relevant Rules

`pip_install`

### Description

Is there a way to add additional dependencies to `pip_install` -- specifically (for example) the library [PyAudio](https://pypi.org/project/PyAudio/), a wrapper for [portaudio](http://www.portaudio.com/) requires portaudio to be installed system-wide. 

Is there a way to teach `pip_install` that, before it can install `PyAudio` it needs to take care of this other dependency `portaudio`?

### Describe the solution you'd like

Some way of saying

```starlark
pip_install(
    name = "pypi",
    python_interpreter_target = "@python_interpreter//:python/install/bin/python3.9",
    requirements = "//bazel-python:requirements.txt",
    deps = [
        # Not sure what goes here
    ],
)
```

### Describe alternatives you've considered

The alternative is of course to use system portaudio. 
Or the package `pyaudio` itself could learn to fetch and compile a version of portaudio it can use.

**Comment by groodt** [comment]
I would suggest the best way to go about that would be for you to write a repository rule that installs that package globally *before*  pip_install is called. Or a rule that wraps pip_install that executes the installation script. 
See https://bazel.build/extending/repo

It’s not hermetic to be installing things globally like that, so it’s not something I believe we should encourage with rules_python.

Another option for you to consider could be to prebuild static wheels with pyaudio linked and push to your own pypi repository / mirror so you can lock against those for your bazel project. It seems the project lets you do that via `python setup.py build --static-link`.

**Comment by odashi** [comment]
FWIW, I ran into a similar problem when I tried to bundle `mysqlclient`, which requires several system libraries at installation.

Since we needed that package only in the final Docker container for serving (and the package does not depend on any other stuff in PyPI), we prepared a base image with `mysqlclient` installed, and used it in the `py_image` rule in rules_docker with a small modification of `sys.path`. In this case the workspace itself maintains its hermeticity, but the artifact contains something from outside.

I think not small number of users may encounter the issue when they needed to bundle something related to the system, and it may be great if we get some guidances about handling the issue.
