### ISSUE TITLE
Include extra dependencies for `entry_point`

### ISSUE THREAD

**Issue by xinbinhuang** [bazelbuild/rules_python#979]
# 🚀 feature request
related: https://github.com/bazelbuild/rules_python/issues/341

### Relevant Rules

`entry_point`

### Description

Currently, the `entry_point` is a pre-generated `py_binary` to expose the `console_scripts`. It works for tools that takes file as input and with limited reliance on module resolution e.g. static analysis tools, `flake8`, `black`. 

However, it doesn't quite work with things that expect dependencies on the import path, which is common for running dev server for web development frameworks, e.g `flask`, `uvicorn`, `strawberry`. In order for these use cases to work, we need a mechanism to properly propagate the import paths when executing the console scripts target.

### Describe the solution you'd like

One solution would be to convert `entry_point` into a macro that dynamically generate `py_binary` on the fly, so that it can take additional `deps` attribute to construct the console scripts `py_binary`.

Roughly can be implemented as below?

In the generated `@pip//:requirements.bzl`
```
load("@rules_python//python:defs.bzl", "py_binary")
load("@pip//:requirements.bzl", "requirement")

def new_entry_point(name, pkg, script = None, **kwargs):
    if not script:
        script = pkg
    entry_point_py = "@{repo_prefix}" + _clean_name(pkg) + "//:{entry_point_prefix}_" + script + ".py"

    py_binary(
        name = name,
        srcs = kwargs.pop("srcs", []) + [entry_point_py],
        main = entry_point_py,
        deps = kwargs.pop("deps", []) + [requirement(pkg)],
        **kwargs
    )
```

In `BUILD.bazel`
```

new_entry_porint(
    name = "strawberry",
    pkg = "strawberry-graphql",
    script = "strawberry",
    deps = [
        ":schema",
    ],
)
```

### Describe alternatives you've considered

use environment variables `PYTHONPATH` when calling `PYTHONPATH=... bazel run ... `. but it's hard and not trivial to figure out all import paths and add to it.

**Comment by rafmagns-skepa-dreag** [comment]
linked PR author asked questions that were never answered on publicly github. would like to see them answered before this issue is closed

**Comment by chrislovecnm** [comment]
@aignas can you take a look?

**Comment by aignas** [comment]
I have been spending a lot of time about the `entry_point` macro these days and I am thinking that the existing solution that we have on the `main` branch does not fully work for all of the usecases. I also see that this ticket is very similar to what I had raised a while ago #543. The #980 has a drawback that we are increasing the API surface and we [2 competing standards](https://xkcd.com/927/).

Current approach of dealing with entry points is:
1. Depend on the `whl_library` to create a `.py` script, that is exposed via `py_binary`. The script is probably created from reading the entrypoints [spec](https://packaging.python.org/en/latest/specifications/entry-points/), but I haven't checked it to be sure.
2. The name of the `py_binary` target has to be prepended with a big prefix in order to ensure that it does not clash with anything already existing in the wheel.
3. The `entry_point` macro makes the generated `py_binary` useable by (hopefully) returning the label to the `entry_point` target and then the user has to create an `alias`.
4. `alias` definition serves an important part of the whole `entry_point` usage because the entry_points might be used by other Python script, which would need using `$(location <pathtoalias>)` to get the location to the python file.

This is a lot and not necessarily easy to maintain and @groodt has mentioned quite a few times that we would like to move away from those macros.

What I would propose to solve this problem is to use build rules instead of repository rules and we should be able to achieve it by doing the following.
1. Ensure that the `entrypoints.txt` file is exposed by the `:pkg` target coming from the `whl_library`
2. Create a macro in `//python:entry_point.bzl` which could be something like:
   ```starlark
   def entry_point(name, pkg, script, deps):
       native.genrule( # generate the `.py` script from the entrypoints.txt to be used in the `py_binary` later)

       py_binary(# use the generated script in the genrule)
   ```

   Note that the `genrule` could be substituted with something more robust, so I am only trying to convey of what actions need to happen.
3. The user can then use the macro as:
   ```starlark
   load("@rules_python//python:entry_point.bzl", "entry_point")
   # or load("@python_3_9//:defs.bzl", "entry_point")
   # or load("@python_versions//3.9:defs.bzl", "entry_point")

   entry_point(
       name = "flake8",
       pkg = "@pypi//flake8",
       script = "flake8",  # could be omitted if there is a single `console_script` in the entrypoints.txt file.
       deps = [
           "@pypi//flake8_bugbear",
           "@pypi//flake8_my_custom_plugin",
       ],
   )
   ```

This way the `entry_point` macro can also be reused in `@rules_pycross` and it should be compatible with `bzlmod` out of the box. The transition support would be also something that could be implemented easily on top.

That way we would not have to worry about extra dependencies and we could also add extra tests to the `entry_point` and decrease the API surface we expose in the hub repos.

**Comment by groodt** [comment]
Yes. This is broadly the direction I would like to see the rules move in. Even for the `requirement` and other convenience rules we are generating inside a very complex repository rule. It is *much* easier to handle these things more cleanly in user-space.

Here is how I would do it.

## For moving `entry_point` to userspace

I would do similar to what you propose. I personally didn't even have support for the `entrypoints.txt` in mind, but I think thats nice and convenient. I was probably just going to expose `(shebang, module, attribute)` which is all that an entrypoint requires anyway.

```
{shebang}
import sys
from {module} import {attribute}
if __name__ == "__main__":
    sys.exit({attribute}())
```

## For moving `requirement`, `whl_requirement`, `data_requirement`, `dist_info_requirement` to userspace

I would do very similar to rules_jvm_external https://github.com/bazelbuild/rules_jvm_external/blob/master/private/rules/artifact.bzl

I would have a default repository name for the common case and a way for people to supply a specific repository if they're doing something more complicated or running with multiple repositories in their repo for whatever reason.

I question why there is any reasonable desire to have such convenient access to what are effectively just filegroups as well. `requirement` I can understand, because that was supported initially in the rules and is probably used heavily, so it justifies a migration path.

The others, I'm really not super clear on why we couldn't simply document the named filegroups and be done with it.

## For removing most of the need for `annotations`

Most of annotations can be replaced with simple `patch` support. If we follow the familiar semantics used elsewhere in bazel where there is `build_file` and `build_file_content` and `patches` a user is empowered to get themselves out of a lot of tricky situations.

`data_exclude_glob` is removed by a patch that deletes the file(s)
`srcs_exclude_glob` is removed by a patch that deletes the file(s)

And being able to swap out a BUILD file in general gives you great flexibility that the rules don't need to have built-in. I'm not sure on the purpose of some of the `copy` attributes in attributes, but those too could perhaps be handled through patching.

cc @rickeylev

**Comment by rickeylev** [comment]
For an entry point with custom dependencies, it has to be done in user space -- such a target is a distinct binary from the "default" entry point binary.

I'm +1 on adding a user-space macro similar to what Ignas and Greg describe. I gtg right now, but the basic API I'm thinking is:

* `py_entry_point_binary` (these are binaries, and the naming scheme of Bazel rules is de-facto <lang>_<detail>_(binary|test|library)).
* Homed in `//python:py_entry_point_binary.bzl`
* Signature:
  * `pkg: Label`, required, label to package providing the necessary dependency
  * `script: str`, optional, defaults to the package name (e.g. `Label.name`). The `{attribute}` portion from Greg's example.
  * `binary_rule: rule`, optional, defaults to `//python:py_binary.bzl#py_binary`, the rule to invoke to build the binary. This allows different binary implementations to be used. Most notably, the version-aware wrappers, but this also permits e.g. things that implement type checking etc.
  * kwargs is passed along to `binary_rule`
  * `main` arg is disallowed; the point of this rule is to generate main for you, after all.

I suppose an optional `module` arg might be prudent for cases where it can't be automatically inferred from the `pkg` arg.

Hm, actually, we could default `binary_rule` to the version-aware rule that isn't pinned to a specific version. This would allow the target to naturally participate in the flag-based version selection logic.

I'm -0 on renaming `script` to `attribute` -- our current api uses `script`, so I would say just continue with that for consistency.

> shebang

The shebang is extraneous; the py_binary rule generates its own executable that ignores the main file's shebang.

re: moving away from the repo-generated macros: Lets move discussion of that to a separate issue. We're all in general agreement about going that direction, but the details and process are beyond the scope of a FR to make it easier to generate/customize an entry point for a package.

**Comment by aignas** [comment]
> I think if we press ahead with this I would also like to see deprecation warnings added to the exisiting implementation of `entry_point`. What do we believe to be a suitable deprecation window given that the rules are not yet 1.0?

Added this to #1363 during my first prototype, please let me know what you think.

> In terms of terminology we should reference, the closest thing to the official spec is outlined here [Entry points specification](https://packaging.python.org/en/latest/specifications/entry-points/#entry-points-specification) in the documentation from the PyPA.

: +1: for this, I'll rename the templating code accordingly.

> I would hope that we can implement this all in Starlark? I don't think there is any need to run a python interpreter for this functionality? Although, the format of the `entry_points.txt` file is meant to be INI, it is probably simple enough to parse in Starlark? Maybe I'm overthinking it...

I was thinking about it but realised that we cannot read a file within a build rule (unlike a repository rule) and it seems that https://github.com/bazelbuild/bazel/issues/14744 specifically said that it is not compatible with the bazel's analysis and execution phase model.

> > * `pkg: Label`, required, label to package providing the necessary dependency
> 
> We certainly require the root package where the entry points are found. I also believe we should support `deps: []`. This should be supported because sometimes metadata for python packages is broken and deps aren't always defined correctly. It should also be defined to enable "plugin" like behaviour. In some cases, entry points are used to provide a plugin like behaviour and we need these deps on the PYTHONPATH for it to work.

`deps` supported in the current iteration of #1363.

> Should we really use `pkg` as the name of the attribute? I understand that it's short, but is `package` more descriptive or accurate?

@rickeylev, using the name of the `pkg` attribute is not possible in the general case, because the macro has to work with:
* `@pypi_pylint//:pkg`
* `@pypi//pylint`
* `@pypi//pylint:pkg`

And what is more, the `pylint` part of string usually goes through a normalization phase, which means that `-` will be replaced with `_` and that is incorrect behaviour in this case IMO.

> > * `script: str`, optional, defaults to the package name (e.g. `Label.name`). The `{attribute}` portion from Greg's example.
> 
> Strictly speaking, an `entry_point` is defined as `(group, name, object reference)`. The most common entry points out there (and the ones we currently have basic support for) and the ones outlined in this issue are called `console_scripts`. These are entry points that are intended for launching commands in your console with stdin, stdout and stderr. This is one of 2 special groups of `entry_point`. The other is `gui_scripts` which are intended for launching gui applications. I've never seen one, so they are probably rare. The distinction is broadly related to Windows anyway according to the docs. All this is to say, that perhaps the rule is more accurately described as `py_console_script_binary`? Or, if we intend to keep `py_entry_point_binary` then this attribute should not be `script`, but rather `console_script_name`. We don't need to support `gui_script` and the other concept of custom entry point groups isn't something we presently support and Im not sure they are even necessary in bazel anyway.

Both `py_console_script_binary` and `py_entry_point_binary` are fine as I agree with you that we should only target to support `console_script` entry points for now.

> My sketch for the rule would look like this given the following `entry_points.txt` in a hypothetical `@pypi//fizzbuzz` package.
> ```
> ...
>     name = "a_console_script_provided_by_foo", # required. bazel needs these.
>     package = "@pypi//fizzbuzz", # required. the root package that provides entry_points.txt
>     script_name = "foo",  # optional. the name of the entry point in the console_script group. required unless script_module and script_attribute are provided
>     script_module = "foomod", # optional. required unless script_name is provided. if script_name is not provided, then both script_module and script_attribute are required
>     script_attribute = "main",# optional. required unless script_name is provided. if script_name is not provided, then both script_module and script_attribute are required
>     deps = [
>         "@pypi//bazz",
>         "@pypi//buzz",
>     ],
> )
> ```

I have not yet implemented the `script_module`, `script_attribute` support yet. I thought that it was really easy, but was wondering if it is needed at this time. Then we would open up the `py_entry_point_binary` to be used in local packages as well and I am not sure if we should ask users create separate directories and have `__main__.py` files in each of them or support `py_entry_point_binary` usage within the context of generating entry points for the functions in the main workspace. I'd like to potentially split the discussion/implementation into a separate issue and scope this only to what is available as `console_scripts` in the `entry_points.txt`.

**Comment by rickeylev** [comment]
> I would hope that we can implement this all in Starlark?  I don't think there is any need to run a python interpreter for this functionality? Although, the format of the entry_points.txt file is meant to be INI, it is probably simple enough to parse in Starlark? Maybe I'm overthinking it...

It depends.

Consuming an ini file to determine what to do requires either:
  1. Logic in a repo rule. Starlark should be able to do this just fine, but a small Python program could, too.
  2. Logic in a build rule. This requires some build tool to run. Likely a small Python program.

None of us really want to add more repo-rule logic, so can we agree that (1) isn't really an option?

Which leaves us with (2), which is a lot of additional plumbing just to abstract an attribute name (I mention this further down, too).

> we should support deps

Yes, that comes via `**kwargs`, which are passed along to whatever `binary_rule` is.

> Should we really use pkg as the name of the attribute? I understand that it's short, but is package more descriptive or accurate?

I'm -0 on a name change to be consistent with the existing `entry_point()` interface.

> Strictly speaking, an entry_point is (group, name object reference); gui vs console vs other groups

Thanks, this is good to know. The spec is, ah, interesting. It also sounds like the entry point name is _supposed_ to be unique, too, so the "group" is somewhat not something we have to expose to users ("Within a distribution, entry point names should be unique. ... the consumer decides how to handle ... conflicts").

> If we are correctly parsing entry_points.txt, then I can't think of a situation they would be necessary

Er, I'm not sure we're talking about the same thing anymore. I don't expect this rule to parse any entry_points.txt file. All it really does is generate the .py file to be passed onto `py_binary(main=...)` and add an entry to `deps`. So all it really needs is (1) the module to import, (2) the attribute from it to import, and (3) the dependency that provides the import.

I'm not entirely against a rule that takes an entry points configuration file as input, however, it's kind of a hassle. It's minimal inputs are, (1) dependency label (2) entry points config file, (3) group name in config file, and (4) name within group (though we could default this to the name arg). No "script attribute" is necessary, as it comes from the config file. (2) has to be generated by a repo rule (or otherwise extracted from the pypi package and made available as a build input), plus a tool has to read that config file back. All of this just to get at a small string (the attribute name to import).

A couple other things in the spec also stick out to me:
  * An entry point can have "extras", which are additional dependencies? Unfortunately, we can't model such dynamic dependencies in Bazel very well. Doing so requires a repo rule to convert the entry points config into something available during the loading phase, so that the different set of dependencies is properly used. _Maybe_ something with computed attributes. Or I have some...interesting...ideas with aspects. In any case, not very clear path here.
  * The entry point names are supposed to be unique, which makes specify the group name somewhat extraneous.

As a user, `py_entry_point_binary(name="foo", config="@pip//fizzbuzz:entry_points", deps=[...])` (which uses the "foo" entry point automagically with additional deps) is very appealing, however, making that Just Work in a clean way that checks all the {correct,cross-platform,cross-version,bzlmod,workspace} boxes is less clear.

So I'd prefer to we defer on having a public rule that takes entrypoints.txt as an input for now. No opinion on if, _internally_, the pip integration and such generates and consumes an entrypoint.txt file; just keep it internal.

> Suggested `py_console_script_binary` name

The gui vs console distinction has me convinced to agree with calling it `py_console_script_binary`. What we're implementing matches that spec. However, let's move it to `//python/entry_points`, otherwise it sounds like an alternative to `py_binary` for a console-based program (i.e. almost all py binaries), which isn't exactly true.

Maybe in some future we can have a `py_gui_script_binary` or a `py_entry_point_binary(gui=True)`, or something, but lets just ignore that for, hopefully, ever. Like you, I've never seen a gui entry point, either.

**Comment by rickeylev** [comment]
Ignas went through the trouble of implementing the "read an ini file to generate the entry point main file" approach, so I let's spec that out a bit.

The gist of his implementation is it feeds the pip-repo generated `dist_info` file group into a rule, which looks for the entry_points.txt file, parses it, and generates a .py file. This file is given as the main for a py_binary. Overall, I think it's pretty good!

To recap the basic inputs for this case:
1. Dependency label that provides the necessary import
2. A thing providing the entry_point.txt config
3. The entry point name within the "console_scripts" group in the entry point config.

I very much like Ignas's design here, so I'm just going to tweak it a bit. The main thing I'm changing from what he has in his PR is adding the entry_point_config arg to decouple the rule from the layout our pip repo rules use.

`pkg`: str, Label, or select() expression, i.e. a dependency value. This value is added to `deps` of the generated `py_binary. Typically the value would be `@pypi_pylint//:pkg`, `@pypi//pylint`, `@pypi//pylint:pkg`, but not necessarily. For example, I might define `//foo:sphinx_with_my_plugins`, or manually configure `http_archive()`s to whl files and have a rule that turns them into py_library-equivalents.

`entry_point_config`: a dependency value, as above. Optional, depending on the `pkg` value type. This is the target that provides an `entry_point.txt` file. If not specified, and the value of `pkg` isn't a select, then use `pkg.label.replace(name="dist_info")` (this is to support the common case of pip.parse() repos). Typically a value like `@pypi//pylint:dist_info`, but not necessarily. I might, for example, vendor whl files and write a rule that makes the entry_point.txt file within them available.

`script`: string, the name from the `console_script` entry point group. Somewhat optional; I think we should infer it from either the `name` arg or the `pkg` arg's name portion of the label.

I'm open to bike shedding the `entry_point_config` name. The simple name of `entry_point` seems like a poor choice because it'll get confused with `script`.

Some example usages would look like:

```
py_console_script_binary(
  name = "pylint",
  pkg = "@pip//pylint",
)
py_console_script_binary(
  name = "fizz",
  pkg = "@pip//fizzbuzz",
  script = "buzz",
)
py_console_script_binary(
  name = "myapp_sphinx",
  pkg = select({
    ":mac": ":whl_to_pylib_mac",
    ":linux": ":whl_to_pylib_linux",
  }),
  entry_point_config = ":gen_entry_points_from_whls",
  script = "sphinx",
  deps = [":myapp_lib"]
)
```

**Comment by aignas** [comment]
@rickeylev, thanks for the comments, a few thoughts on your suggestions:

> `pkg`: str, Label, or select() expression, i.e. a dependency value. This value is added to `deps` of the generated `py_binary`. Typically the value would be `@pypi_pylint//:pkg`, `@pypi//pylint`, `@pypi//pylint:pkg`, but not necessarily. For example, I might define `//foo:sphinx_with_my_plugins`, or manually configure `http_archive()`s to whl files and have a rule that turns them into py_library-equivalents.

+1 here, however, I think it only matters when we are thinking about it in the context of below:

> `entry_point_config`: a dependency value, as above. Optional, depending on the `pkg` value type. This is the target that provides an `entry_point.txt` file. If not specified, and the value of `pkg` isn't a select, then use `pkg.label.replace(name="dist_info")` (this is to support the common case of pip.parse() repos). Typically a value like `@pypi//pylint:dist_info`, but not necessarily. I might, for example, vendor whl files and write a rule that makes the entry_point.txt file within them available.

I guess the most direct connection between my implementation and what you are proposing here would be to have a `dist_info` attribute which would default to `pkg.replace(...)` if unspecified, but the user could supply it's own `entry_points.txt` file/filegroup which we could happily consume.

> `script`: string, the name from the `console_script` entry point group. Somewhat optional; I think we should infer it from either the `name` arg or the `pkg` arg's name portion of the label.

So given that there will be no module named `foo-bar` and it will be normalized to `foo_bar` within the Python imports, it would potentially be safe to implement an auto-detection algorithm where we take the `name` of the `py_console_script_binary` and check if there is any key that satisfies `key.replace("-", "_").replace(".", "_") == name.replace("-", "_").replace(".", "_")`. That way we could make the API even better.

> I'm open to bike shedding the `entry_point_config` name. The simple name of `entry_point` seems like a poor choice because it'll get confused with `script`.
> 
> Some example usages would look like:
> ```starlark
> py_console_script_binary(
>   name = "pylint",
>   pkg = "@pip//pylint",
> )
> py_console_script_binary(
>   name = "fizz",
>   pkg = "@pip//fizzbuzz",
>   script = "buzz",
> )
> ```

These LGTM.
>```starlark
> py_console_script_binary(
>   name = "myapp_sphinx",
>   pkg = select({
>     ":mac": ":whl_to_pylib_mac",
>     ":linux": ":whl_to_pylib_linux",
>   }),
>   entry_points_txt = ":gen_entry_points_from_whls",
>   script = "sphinx",
>   deps = [":myapp_lib"]
> )
> ```

I would propose to have `entry_points_txt`, which is similar to `entry_points_config` but distinct enough from it and is almost the same thing as is described in https://packaging.python.org/en/latest/specifications/entry-points/#data-model.

**Comment by rickeylev** [comment]
> So given that there will be no module named `foo-bar` and it will be normalized to `foo_bar` within the Python imports, it would potentially be safe to implement an auto-detection algorithm where we take the `name` of the `py_console_script_binary` and check if there is any key that satisfies `key.replace("-", "_").replace(".", "_") == name.replace("-", "_").replace(".", "_")`. That way we could make the API even better.

I don't follow -- why do we have to normalize hyphen to underscore? I don't see anything in the entry points spec that indicates that. An entry point like `foo-bar = foomod:main` is valid AFAIK, and I'm pretty sure I've seen these in practice.

I would just take name as-is without normalizing because it's simpler. If a Bazel target name can't exactly match the entry point name, then the `script` arg is available.

**Comment by rickeylev** [comment]
re: `entry_points_txt` name: +1, nice name that directly represents what's desired.

**Comment by aignas** [comment]
> > So given that there will be no module named `foo-bar` and it will be normalized to `foo_bar` within the Python imports, it would potentially be safe to implement an auto-detection algorithm where we take the `name` of the `py_console_script_binary` and check if there is any key that satisfies `key.replace("-", "_").replace(".", "_") == name.replace("-", "_").replace(".", "_")`. That way we could make the API even better.
> 
> I don't follow -- why do we have to normalize hyphen to underscore? I don't see anything in the entry points spec that indicates that. An entry point like `foo-bar = foomod:main` is valid AFAIK, and I'm pretty sure I've seen these in practice.
> 
> I would just take name as-is without normalizing because it's simpler. If a Bazel target name can't exactly match the entry point name, then the `script` arg is available.

I was confused and thought that the restrictions outlined in https://github.com/bazelbuild/bazel/issues/6841 applied to both, the target names and the packages, but re-reading this makes me realize that it is not the case and the limitation only applies to package names.

My initial thinking was that if bazel imposes a restriction on target names, then our matching of the entry_point should normalize strings to make it more useful, but that logic is flawed, so I am happy to just use the `name` for guessing.
