### ISSUE TITLE
Provide a way to publish Python packages

### ISSUE THREAD

**Issue by calder** [bazelbuild/rules_python#99]
Add a rule for building Python packages for distribution via PyPi. See https://github.com/horia141/bazel-pypi-package for an initial defunct attempt this.

**Comment by rkhir** [comment]
Hello, is there an update on this issue? Or perhaps an alternative solution to publish Python packages?

**Comment by alexeagle** [comment]
We now need this for rules_python itself, as we want to publish the runfiles library as a wheel to pypi.
I tried the simple thing of using `twine` via https://github.com/pypa/gh-action-pypi-publish but it failed our release https://github.com/bazelbuild/rules_python/actions/runs/4001340558/jobs/6867466794

In any event, I think this isn't a good solution because it's non-hermetic - you need python and `twine` and other stuff on the environment where you publish the wheel. I think we need a proper target that can be used with `bazel run` that does the publish, assuming nothing about the machine where it's run.

**Comment by alexeagle** [comment]
0.18.2 should be released today which finally creates a `[name].publish` target on py_wheel.
